export interface Iso3166Alpha2Country {
  value: string;
  label: string;
}

const ISO_3166_ALPHA2_COUNTRIES_UNSORTED: Iso3166Alpha2Country[] = [
  { value: 'AD', label: 'Андорра' },
  { value: 'AE', label: 'ОАЭ' },
  { value: 'AF', label: 'Афганистан' },
  { value: 'AG', label: 'Антигуа и Барбуда' },
  { value: 'AI', label: 'Ангилья' },
  { value: 'AL', label: 'Албания' },
  { value: 'AM', label: 'Армения' },
  { value: 'AO', label: 'Ангола' },
  { value: 'AQ', label: 'Антарктида' },
  { value: 'AR', label: 'Аргентина' },
  { value: 'AS', label: 'Американское Самоа' },
  { value: 'AT', label: 'Австрия' },
  { value: 'AU', label: 'Австралия' },
  { value: 'AW', label: 'Аруба' },
  { value: 'AX', label: 'Аландские острова' },
  { value: 'AZ', label: 'Азербайджан' },
  { value: 'BA', label: 'Босния и Герцеговина' },
  { value: 'BB', label: 'Барбадос' },
  { value: 'BD', label: 'Бангладеш' },
  { value: 'BE', label: 'Бельгия' },
  { value: 'BF', label: 'Буркина-Фасо' },
  { value: 'BG', label: 'Болгария' },
  { value: 'BH', label: 'Бахрейн' },
  { value: 'BI', label: 'Бурунди' },
  { value: 'BJ', label: 'Бенин' },
  { value: 'BL', label: 'Сен-Бартелеми' },
  { value: 'BM', label: 'Бермуды' },
  { value: 'BN', label: 'Бруней' },
  { value: 'BO', label: 'Боливия' },
  { value: 'BQ', label: 'Бонэйр, Синт-Эстатиус и Саба' },
  { value: 'BR', label: 'Бразилия' },
  { value: 'BS', label: 'Багамы' },
  { value: 'BT', label: 'Бутан' },
  { value: 'BV', label: 'Остров Буве' },
  { value: 'BW', label: 'Ботсвана' },
  { value: 'BY', label: 'Беларусь' },
  { value: 'BZ', label: 'Белиз' },
  { value: 'CA', label: 'Канада' },
  { value: 'CC', label: 'Кокосовые острова' },
  { value: 'CD', label: 'ДР Конго' },
  { value: 'CF', label: 'ЦАР' },
  { value: 'CG', label: 'Республика Конго' },
  { value: 'CH', label: 'Швейцария' },
  { value: 'CI', label: 'Кот-д’Ивуар' },
  { value: 'CK', label: 'Острова Кука' },
  { value: 'CL', label: 'Чили' },
  { value: 'CM', label: 'Камерун' },
  { value: 'CN', label: 'Китай' },
  { value: 'CO', label: 'Колумбия' },
  { value: 'CR', label: 'Коста-Рика' },
  { value: 'CU', label: 'Куба' },
  { value: 'CV', label: 'Кабо-Верде' },
  { value: 'CW', label: 'Кюрасао' },
  { value: 'CX', label: 'Остров Рождества' },
  { value: 'CY', label: 'Кипр' },
  { value: 'CZ', label: 'Чехия' },
  { value: 'DE', label: 'Германия' },
  { value: 'DJ', label: 'Джибути' },
  { value: 'DK', label: 'Дания' },
  { value: 'DM', label: 'Доминика' },
  { value: 'DO', label: 'Доминиканская Республика' },
  { value: 'DZ', label: 'Алжир' },
  { value: 'EC', label: 'Эквадор' },
  { value: 'EE', label: 'Эстония' },
  { value: 'EG', label: 'Египет' },
  { value: 'EH', label: 'Западная Сахара' },
  { value: 'ER', label: 'Эритрея' },
  { value: 'ES', label: 'Испания' },
  { value: 'ET', label: 'Эфиопия' },
  { value: 'FI', label: 'Финляндия' },
  { value: 'FJ', label: 'Фиджи' },
  { value: 'FK', label: 'Фолклендские острова' },
  { value: 'FM', label: 'Микронезия' },
  { value: 'FO', label: 'Фарерские острова' },
  { value: 'FR', label: 'Франция' },
  { value: 'GA', label: 'Габон' },
  { value: 'GB', label: 'Великобритания' },
  { value: 'GD', label: 'Гренада' },
  { value: 'GE', label: 'Грузия' },
  { value: 'GF', label: 'Французская Гвиана' },
  { value: 'GG', label: 'Гернси' },
  { value: 'GH', label: 'Гана' },
  { value: 'GI', label: 'Гибралтар' },
  { value: 'GL', label: 'Гренландия' },
  { value: 'GM', label: 'Гамбия' },
  { value: 'GN', label: 'Гвинея' },
  { value: 'GP', label: 'Гваделупа' },
  { value: 'GQ', label: 'Экваториальная Гвинея' },
  { value: 'GR', label: 'Греция' },
  { value: 'GS', label: 'Южная Георгия и Южные Сандвичевы острова' },
  { value: 'GT', label: 'Гватемала' },
  { value: 'GU', label: 'Гуам' },
  { value: 'GW', label: 'Гвинея-Бисау' },
  { value: 'GY', label: 'Гайана' },
  { value: 'HK', label: 'Гонконг' },
  { value: 'HM', label: 'Остров Херд и острова Макдональд' },
  { value: 'HN', label: 'Гондурас' },
  { value: 'HR', label: 'Хорватия' },
  { value: 'HT', label: 'Гаити' },
  { value: 'HU', label: 'Венгрия' },
  { value: 'ID', label: 'Индонезия' },
  { value: 'IE', label: 'Ирландия' },
  { value: 'IL', label: 'Израиль' },
  { value: 'IM', label: 'Остров Мэн' },
  { value: 'IN', label: 'Индия' },
  { value: 'IO', label: 'Британская территория в Индийском океане' },
  { value: 'IQ', label: 'Ирак' },
  { value: 'IR', label: 'Иран' },
  { value: 'IS', label: 'Исландия' },
  { value: 'IT', label: 'Италия' },
  { value: 'JE', label: 'Джерси' },
  { value: 'JM', label: 'Ямайка' },
  { value: 'JO', label: 'Иордания' },
  { value: 'JP', label: 'Япония' },
  { value: 'KE', label: 'Кения' },
  { value: 'KG', label: 'Кыргызстан' },
  { value: 'KH', label: 'Камбоджа' },
  { value: 'KI', label: 'Кирибати' },
  { value: 'KM', label: 'Коморы' },
  { value: 'KN', label: 'Сент-Китс и Невис' },
  { value: 'KP', label: 'КНДР' },
  { value: 'KR', label: 'Республика Корея' },
  { value: 'KW', label: 'Кувейт' },
  { value: 'KY', label: 'Каймановы острова' },
  { value: 'KZ', label: 'Казахстан' },
  { value: 'LA', label: 'Лаос' },
  { value: 'LB', label: 'Ливан' },
  { value: 'LC', label: 'Сент-Люсия' },
  { value: 'LI', label: 'Лихтенштейн' },
  { value: 'LK', label: 'Шри-Ланка' },
  { value: 'LR', label: 'Либерия' },
  { value: 'LS', label: 'Лесото' },
  { value: 'LT', label: 'Литва' },
  { value: 'LU', label: 'Люксембург' },
  { value: 'LV', label: 'Латвия' },
  { value: 'LY', label: 'Ливия' },
  { value: 'MA', label: 'Марокко' },
  { value: 'MC', label: 'Монако' },
  { value: 'MD', label: 'Молдова' },
  { value: 'ME', label: 'Черногория' },
  { value: 'MF', label: 'Сен-Мартен' },
  { value: 'MG', label: 'Мадагаскар' },
  { value: 'MH', label: 'Маршалловы Острова' },
  { value: 'MK', label: 'Северная Македония' },
  { value: 'ML', label: 'Мали' },
  { value: 'MM', label: 'Мьянма' },
  { value: 'MN', label: 'Монголия' },
  { value: 'MO', label: 'Макао' },
  { value: 'MP', label: 'Северные Марианские острова' },
  { value: 'MQ', label: 'Мартиника' },
  { value: 'MR', label: 'Мавритания' },
  { value: 'MS', label: 'Монтсеррат' },
  { value: 'MT', label: 'Мальта' },
  { value: 'MU', label: 'Маврикий' },
  { value: 'MV', label: 'Мальдивы' },
  { value: 'MW', label: 'Малави' },
  { value: 'MX', label: 'Мексика' },
  { value: 'MY', label: 'Малайзия' },
  { value: 'MZ', label: 'Мозамбик' },
  { value: 'NA', label: 'Намибия' },
  { value: 'NC', label: 'Новая Каледония' },
  { value: 'NE', label: 'Нигер' },
  { value: 'NF', label: 'Остров Норфолк' },
  { value: 'NG', label: 'Нигерия' },
  { value: 'NI', label: 'Никарагуа' },
  { value: 'NL', label: 'Нидерланды' },
  { value: 'NO', label: 'Норвегия' },
  { value: 'NP', label: 'Непал' },
  { value: 'NR', label: 'Науру' },
  { value: 'NU', label: 'Ниуэ' },
  { value: 'NZ', label: 'Новая Зеландия' },
  { value: 'OM', label: 'Оман' },
  { value: 'PA', label: 'Панама' },
  { value: 'PE', label: 'Перу' },
  { value: 'PF', label: 'Французская Полинезия' },
  { value: 'PG', label: 'Папуа — Новая Гвинея' },
  { value: 'PH', label: 'Филиппины' },
  { value: 'PK', label: 'Пакистан' },
  { value: 'PL', label: 'Польша' },
  { value: 'PM', label: 'Сен-Пьер и Микелон' },
  { value: 'PN', label: 'Острова Питкэрн' },
  { value: 'PR', label: 'Пуэрто-Рико' },
  { value: 'PS', label: 'Палестина' },
  { value: 'PT', label: 'Португалия' },
  { value: 'PW', label: 'Палау' },
  { value: 'PY', label: 'Парагвай' },
  { value: 'QA', label: 'Катар' },
  { value: 'RE', label: 'Реюньон' },
  { value: 'RO', label: 'Румыния' },
  { value: 'RS', label: 'Сербия' },
  { value: 'RU', label: 'Россия' },
  { value: 'RW', label: 'Руанда' },
  { value: 'SA', label: 'Саудовская Аравия' },
  { value: 'SB', label: 'Соломоновы Острова' },
  { value: 'SC', label: 'Сейшелы' },
  { value: 'SD', label: 'Судан' },
  { value: 'SE', label: 'Швеция' },
  { value: 'SG', label: 'Сингапур' },
  { value: 'SH', label: 'Остров Святой Елены' },
  { value: 'SI', label: 'Словения' },
  { value: 'SJ', label: 'Шпицберген и Ян-Майен' },
  { value: 'SK', label: 'Словакия' },
  { value: 'SL', label: 'Сьерра-Леоне' },
  { value: 'SM', label: 'Сан-Марино' },
  { value: 'SN', label: 'Сенегал' },
  { value: 'SO', label: 'Сомали' },
  { value: 'SR', label: 'Суринам' },
  { value: 'SS', label: 'Южный Судан' },
  { value: 'ST', label: 'Сан-Томе и Принсипи' },
  { value: 'SV', label: 'Сальвадор' },
  { value: 'SX', label: 'Синт-Мартен' },
  { value: 'SY', label: 'Сирия' },
  { value: 'SZ', label: 'Эсватини' },
  { value: 'TC', label: 'Теркс и Кайкос' },
  { value: 'TD', label: 'Чад' },
  { value: 'TF', label: 'Французские Южные территории' },
  { value: 'TG', label: 'Того' },
  { value: 'TH', label: 'Таиланд' },
  { value: 'TJ', label: 'Таджикистан' },
  { value: 'TK', label: 'Токелау' },
  { value: 'TL', label: 'Восточный Тимор' },
  { value: 'TM', label: 'Туркменистан' },
  { value: 'TN', label: 'Тунис' },
  { value: 'TO', label: 'Тонга' },
  { value: 'TR', label: 'Турция' },
  { value: 'TT', label: 'Тринидад и Тобаго' },
  { value: 'TV', label: 'Тувалу' },
  { value: 'TW', label: 'Тайвань' },
  { value: 'TZ', label: 'Танзания' },
  { value: 'UA', label: 'Украина' },
  { value: 'UG', label: 'Уганда' },
  { value: 'UM', label: 'Внешние малые острова США' },
  { value: 'US', label: 'США' },
  { value: 'UY', label: 'Уругвай' },
  { value: 'UZ', label: 'Узбекистан' },
  { value: 'VA', label: 'Ватикан' },
  { value: 'VC', label: 'Сент-Винсент и Гренадины' },
  { value: 'VE', label: 'Венесуэла' },
  { value: 'VG', label: 'Виргинские острова (Великобритания)' },
  { value: 'VI', label: 'Виргинские острова (США)' },
  { value: 'VN', label: 'Вьетнам' },
  { value: 'VU', label: 'Вануату' },
  { value: 'WF', label: 'Уоллис и Футуна' },
  { value: 'WS', label: 'Самоа' },
  { value: 'YE', label: 'Йемен' },
  { value: 'YT', label: 'Майотта' },
  { value: 'ZA', label: 'ЮАР' },
  { value: 'ZM', label: 'Замбия' },
  { value: 'ZW', label: 'Зимбабве' },
];

export const ISO_3166_ALPHA2_COUNTRIES: Iso3166Alpha2Country[] = [
  ...ISO_3166_ALPHA2_COUNTRIES_UNSORTED,
].sort((a, b) => a.label.localeCompare(b.label, 'ru'));

export const PLAYER_COUNTRY_OPTIONS: Iso3166Alpha2Country[] = [
  { value: '', label: 'Не выбрано' },
  ...ISO_3166_ALPHA2_COUNTRIES,
];
