package com.nextpari.app.feature.profile

import java.text.Collator
import java.util.Locale

data class IsoCountry(val value: String, val label: String)

object Iso3166Countries {
    val unsorted: List<IsoCountry> = listOf(
        IsoCountry("AD", "Андорра"),
        IsoCountry("AE", "ОАЭ"),
        IsoCountry("AF", "Афганистан"),
        IsoCountry("AG", "Антигуа и Барбуда"),
        IsoCountry("AI", "Ангилья"),
        IsoCountry("AL", "Албания"),
        IsoCountry("AM", "Армения"),
        IsoCountry("AO", "Ангола"),
        IsoCountry("AQ", "Антарктида"),
        IsoCountry("AR", "Аргентина"),
        IsoCountry("AS", "Американское Самоа"),
        IsoCountry("AT", "Австрия"),
        IsoCountry("AU", "Австралия"),
        IsoCountry("AW", "Аруба"),
        IsoCountry("AX", "Аландские острова"),
        IsoCountry("AZ", "Азербайджан"),
        IsoCountry("BA", "Босния и Герцеговина"),
        IsoCountry("BB", "Барбадос"),
        IsoCountry("BD", "Бангладеш"),
        IsoCountry("BE", "Бельгия"),
        IsoCountry("BF", "Буркина-Фасо"),
        IsoCountry("BG", "Болгария"),
        IsoCountry("BH", "Бахрейн"),
        IsoCountry("BI", "Бурунди"),
        IsoCountry("BJ", "Бенин"),
        IsoCountry("BL", "Сен-Бартелеми"),
        IsoCountry("BM", "Бермуды"),
        IsoCountry("BN", "Бруней"),
        IsoCountry("BO", "Боливия"),
        IsoCountry("BQ", "Бонэйр, Синт-Эстатиус и Саба"),
        IsoCountry("BR", "Бразилия"),
        IsoCountry("BS", "Багамы"),
        IsoCountry("BT", "Бутан"),
        IsoCountry("BV", "Остров Буве"),
        IsoCountry("BW", "Ботсвана"),
        IsoCountry("BY", "Беларусь"),
        IsoCountry("BZ", "Белиз"),
        IsoCountry("CA", "Канада"),
        IsoCountry("CC", "Кокосовые острова"),
        IsoCountry("CD", "ДР Конго"),
        IsoCountry("CF", "ЦАР"),
        IsoCountry("CG", "Республика Конго"),
        IsoCountry("CH", "Швейцария"),
        IsoCountry("CI", "Кот-д’Ивуар"),
        IsoCountry("CK", "Острова Кука"),
        IsoCountry("CL", "Чили"),
        IsoCountry("CM", "Камерун"),
        IsoCountry("CN", "Китай"),
        IsoCountry("CO", "Колумбия"),
        IsoCountry("CR", "Коста-Рика"),
        IsoCountry("CU", "Куба"),
        IsoCountry("CV", "Кабо-Верде"),
        IsoCountry("CW", "Кюрасао"),
        IsoCountry("CX", "Остров Рождества"),
        IsoCountry("CY", "Кипр"),
        IsoCountry("CZ", "Чехия"),
        IsoCountry("DE", "Германия"),
        IsoCountry("DJ", "Джибути"),
        IsoCountry("DK", "Дания"),
        IsoCountry("DM", "Доминика"),
        IsoCountry("DO", "Доминиканская Республика"),
        IsoCountry("DZ", "Алжир"),
        IsoCountry("EC", "Эквадор"),
        IsoCountry("EE", "Эстония"),
        IsoCountry("EG", "Египет"),
        IsoCountry("EH", "Западная Сахара"),
        IsoCountry("ER", "Эритрея"),
        IsoCountry("ES", "Испания"),
        IsoCountry("ET", "Эфиопия"),
        IsoCountry("FI", "Финляндия"),
        IsoCountry("FJ", "Фиджи"),
        IsoCountry("FK", "Фолклендские острова"),
        IsoCountry("FM", "Микронезия"),
        IsoCountry("FO", "Фарерские острова"),
        IsoCountry("FR", "Франция"),
        IsoCountry("GA", "Габон"),
        IsoCountry("GB", "Великобритания"),
        IsoCountry("GD", "Гренада"),
        IsoCountry("GE", "Грузия"),
        IsoCountry("GF", "Французская Гвиана"),
        IsoCountry("GG", "Гернси"),
        IsoCountry("GH", "Гана"),
        IsoCountry("GI", "Гибралтар"),
        IsoCountry("GL", "Гренландия"),
        IsoCountry("GM", "Гамбия"),
        IsoCountry("GN", "Гвинея"),
        IsoCountry("GP", "Гваделупа"),
        IsoCountry("GQ", "Экваториальная Гвинея"),
        IsoCountry("GR", "Греция"),
        IsoCountry("GS", "Южная Георгия и Южные Сандвичевы острова"),
        IsoCountry("GT", "Гватемала"),
        IsoCountry("GU", "Гуам"),
        IsoCountry("GW", "Гвинея-Бисау"),
        IsoCountry("GY", "Гайана"),
        IsoCountry("HK", "Гонконг"),
        IsoCountry("HM", "Остров Херд и острова Макдональд"),
        IsoCountry("HN", "Гондурас"),
        IsoCountry("HR", "Хорватия"),
        IsoCountry("HT", "Гаити"),
        IsoCountry("HU", "Венгрия"),
        IsoCountry("ID", "Индонезия"),
        IsoCountry("IE", "Ирландия"),
        IsoCountry("IL", "Израиль"),
        IsoCountry("IM", "Остров Мэн"),
        IsoCountry("IN", "Индия"),
        IsoCountry("IO", "Британская территория в Индийском океане"),
        IsoCountry("IQ", "Ирак"),
        IsoCountry("IR", "Иран"),
        IsoCountry("IS", "Исландия"),
        IsoCountry("IT", "Италия"),
        IsoCountry("JE", "Джерси"),
        IsoCountry("JM", "Ямайка"),
        IsoCountry("JO", "Иордания"),
        IsoCountry("JP", "Япония"),
        IsoCountry("KE", "Кения"),
        IsoCountry("KG", "Кыргызстан"),
        IsoCountry("KH", "Камбоджа"),
        IsoCountry("KI", "Кирибати"),
        IsoCountry("KM", "Коморы"),
        IsoCountry("KN", "Сент-Китс и Невис"),
        IsoCountry("KP", "КНДР"),
        IsoCountry("KR", "Республика Корея"),
        IsoCountry("KW", "Кувейт"),
        IsoCountry("KY", "Каймановы острова"),
        IsoCountry("KZ", "Казахстан"),
        IsoCountry("LA", "Лаос"),
        IsoCountry("LB", "Ливан"),
        IsoCountry("LC", "Сент-Люсия"),
        IsoCountry("LI", "Лихтенштейн"),
        IsoCountry("LK", "Шри-Ланка"),
        IsoCountry("LR", "Либерия"),
        IsoCountry("LS", "Лесото"),
        IsoCountry("LT", "Литва"),
        IsoCountry("LU", "Люксембург"),
        IsoCountry("LV", "Латвия"),
        IsoCountry("LY", "Ливия"),
        IsoCountry("MA", "Марокко"),
        IsoCountry("MC", "Монако"),
        IsoCountry("MD", "Молдова"),
        IsoCountry("ME", "Черногория"),
        IsoCountry("MF", "Сен-Мартен"),
        IsoCountry("MG", "Мадагаскар"),
        IsoCountry("MH", "Маршалловы Острова"),
        IsoCountry("MK", "Северная Македония"),
        IsoCountry("ML", "Мали"),
        IsoCountry("MM", "Мьянма"),
        IsoCountry("MN", "Монголия"),
        IsoCountry("MO", "Макао"),
        IsoCountry("MP", "Северные Марианские острова"),
        IsoCountry("MQ", "Мартиника"),
        IsoCountry("MR", "Мавритания"),
        IsoCountry("MS", "Монтсеррат"),
        IsoCountry("MT", "Мальта"),
        IsoCountry("MU", "Маврикий"),
        IsoCountry("MV", "Мальдивы"),
        IsoCountry("MW", "Малави"),
        IsoCountry("MX", "Мексика"),
        IsoCountry("MY", "Малайзия"),
        IsoCountry("MZ", "Мозамбик"),
        IsoCountry("NA", "Намибия"),
        IsoCountry("NC", "Новая Каледония"),
        IsoCountry("NE", "Нигер"),
        IsoCountry("NF", "Остров Норфолк"),
        IsoCountry("NG", "Нигерия"),
        IsoCountry("NI", "Никарагуа"),
        IsoCountry("NL", "Нидерланды"),
        IsoCountry("NO", "Норвегия"),
        IsoCountry("NP", "Непал"),
        IsoCountry("NR", "Науру"),
        IsoCountry("NU", "Ниуэ"),
        IsoCountry("NZ", "Новая Зеландия"),
        IsoCountry("OM", "Оман"),
        IsoCountry("PA", "Панама"),
        IsoCountry("PE", "Перу"),
        IsoCountry("PF", "Французская Полинезия"),
        IsoCountry("PG", "Папуа — Новая Гвинея"),
        IsoCountry("PH", "Филиппины"),
        IsoCountry("PK", "Пакистан"),
        IsoCountry("PL", "Польша"),
        IsoCountry("PM", "Сен-Пьер и Микелон"),
        IsoCountry("PN", "Острова Питкэрн"),
        IsoCountry("PR", "Пуэрто-Рико"),
        IsoCountry("PS", "Палестина"),
        IsoCountry("PT", "Португалия"),
        IsoCountry("PW", "Палау"),
        IsoCountry("PY", "Парагвай"),
        IsoCountry("QA", "Катар"),
        IsoCountry("RE", "Реюньон"),
        IsoCountry("RO", "Румыния"),
        IsoCountry("RS", "Сербия"),
        IsoCountry("RU", "Россия"),
        IsoCountry("RW", "Руанда"),
        IsoCountry("SA", "Саудовская Аравия"),
        IsoCountry("SB", "Соломоновы Острова"),
        IsoCountry("SC", "Сейшелы"),
        IsoCountry("SD", "Судан"),
        IsoCountry("SE", "Швеция"),
        IsoCountry("SG", "Сингапур"),
        IsoCountry("SH", "Остров Святой Елены"),
        IsoCountry("SI", "Словения"),
        IsoCountry("SJ", "Шпицберген и Ян-Майен"),
        IsoCountry("SK", "Словакия"),
        IsoCountry("SL", "Сьерра-Леоне"),
        IsoCountry("SM", "Сан-Марино"),
        IsoCountry("SN", "Сенегал"),
        IsoCountry("SO", "Сомали"),
        IsoCountry("SR", "Суринам"),
        IsoCountry("SS", "Южный Судан"),
        IsoCountry("ST", "Сан-Томе и Принсипи"),
        IsoCountry("SV", "Сальвадор"),
        IsoCountry("SX", "Синт-Мартен"),
        IsoCountry("SY", "Сирия"),
        IsoCountry("SZ", "Эсватини"),
        IsoCountry("TC", "Теркс и Кайкос"),
        IsoCountry("TD", "Чад"),
        IsoCountry("TF", "Французские Южные территории"),
        IsoCountry("TG", "Того"),
        IsoCountry("TH", "Таиланд"),
        IsoCountry("TJ", "Таджикистан"),
        IsoCountry("TK", "Токелау"),
        IsoCountry("TL", "Восточный Тимор"),
        IsoCountry("TM", "Туркменистан"),
        IsoCountry("TN", "Тунис"),
        IsoCountry("TO", "Тонга"),
        IsoCountry("TR", "Турция"),
        IsoCountry("TT", "Тринидад и Тобаго"),
        IsoCountry("TV", "Тувалу"),
        IsoCountry("TW", "Тайвань"),
        IsoCountry("TZ", "Танзания"),
        IsoCountry("UA", "Украина"),
        IsoCountry("UG", "Уганда"),
        IsoCountry("UM", "Внешние малые острова США"),
        IsoCountry("US", "США"),
        IsoCountry("UY", "Уругвай"),
        IsoCountry("UZ", "Узбекистан"),
        IsoCountry("VA", "Ватикан"),
        IsoCountry("VC", "Сент-Винсент и Гренадины"),
        IsoCountry("VE", "Венесуэла"),
        IsoCountry("VG", "Виргинские острова (Великобритания)"),
        IsoCountry("VI", "Виргинские острова (США)"),
        IsoCountry("VN", "Вьетнам"),
        IsoCountry("VU", "Вануату"),
        IsoCountry("WF", "Уоллис и Футуна"),
        IsoCountry("WS", "Самоа"),
        IsoCountry("YE", "Йемен"),
        IsoCountry("YT", "Майотта"),
        IsoCountry("ZA", "ЮАР"),
        IsoCountry("ZM", "Замбия"),
        IsoCountry("ZW", "Зимбабве"),
    )

    val countries: List<IsoCountry> = unsorted.sortedWith(
        compareBy(Collator.getInstance(Locale("ru", "RU"))) { it.label },
    )

    val playerOptions: List<IsoCountry> = listOf(IsoCountry("", "Не выбрано")) + countries
}
