services:
  - type: web
    name: nextpari-lsports-inplay
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
