// AUTO-GENERATED by android/tools/import_nextpari_web_icons.mjs
// Source: Lucide Icons 0.446.0 (ISC) — same version as web lucide-react.
// Do not hand-edit path geometry. Rerun the importer if Lucide is upgraded.

package com.nextpari.app.core.ui.icons

import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp
import androidx.compose.material3.Icon
import androidx.compose.material3.LocalContentColor
import java.util.concurrent.ConcurrentHashMap

internal object NextpariLucideGeometry {
    /** Lucide plus @ 0.446.0, ISC. */
    val Plus = arrayOf(
            "M5 12h14",
            "M12 5v14",
    )

    /** Lucide moon @ 0.446.0, ISC. */
    val Moon = arrayOf(
            "M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z",
    )

    /** Lucide sun @ 0.446.0, ISC. */
    val Sun = arrayOf(
            "M16,12A4,4 0 1 1 8,12A4,4 0 1 1 16,12",
            "M12 2v2",
            "M12 20v2",
            "m4.93 4.93 1.41 1.41",
            "m17.66 17.66 1.41 1.41",
            "M2 12h2",
            "M20 12h2",
            "m6.34 17.66-1.41 1.41",
            "m19.07 4.93-1.41 1.41",
    )

    /** Lucide settings @ 0.446.0, ISC. */
    val Settings = arrayOf(
            "M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z",
            "M15,12A3,3 0 1 1 9,12A3,3 0 1 1 15,12",
    )

    /** Lucide search @ 0.446.0, ISC. */
    val Search = arrayOf(
            "M19,11A8,8 0 1 1 3,11A8,8 0 1 1 19,11",
            "m21 21-4.3-4.3",
    )

    /** Lucide chevron-down @ 0.446.0, ISC. */
    val ChevronDown = arrayOf(
            "m6 9 6 6 6-6",
    )

    /** Lucide chevron-right @ 0.446.0, ISC. */
    val ChevronRight = arrayOf(
            "m9 18 6-6-6-6",
    )

    /** Lucide chevron-left @ 0.446.0, ISC. */
    val ChevronLeft = arrayOf(
            "m15 18-6-6 6-6",
    )

    /** Lucide chevron-up @ 0.446.0, ISC. */
    val ChevronUp = arrayOf(
            "m18 15-6-6-6 6",
    )

    /** Lucide flame @ 0.446.0, ISC. */
    val Flame = arrayOf(
            "M8.5 14.5A2.5 2.5 0 0 0 11 12c0-1.38-.5-2-1-3-1.072-2.143-.224-4.054 2-6 .5 2.5 2 4.9 4 6.5 2 1.6 3 3.5 3 5.5a7 7 0 1 1-14 0c0-1.153.433-2.294 1-3a2.5 2.5 0 0 0 2.5 2.5z",
    )

    /** Lucide trophy @ 0.446.0, ISC. */
    val Trophy = arrayOf(
            "M6 9H4.5a2.5 2.5 0 0 1 0-5H6",
            "M18 9h1.5a2.5 2.5 0 0 0 0-5H18",
            "M4 22h16",
            "M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22",
            "M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22",
            "M18 2H6v7a6 6 0 0 0 12 0V2Z",
    )

    /** Lucide gamepad-2 @ 0.446.0, ISC. */
    val Gamepad2 = arrayOf(
            "M6,11L10,11",
            "M8,9L8,13",
            "M15,12L15.01,12",
            "M18,10L18.01,10",
            "M17.32 5H6.68a4 4 0 0 0-3.978 3.59c-.006.052-.01.101-.017.152C2.604 9.416 2 14.456 2 16a3 3 0 0 0 3 3c1 0 1.5-.5 2-1l1.414-1.414A2 2 0 0 1 9.828 16h4.344a2 2 0 0 1 1.414.586L17 18c.5.5 1 1 2 1a3 3 0 0 0 3-3c0-1.545-.604-6.584-.685-7.258-.007-.05-.011-.1-.017-.151A4 4 0 0 0 17.32 5z",
    )

    /** Lucide dices @ 0.446.0, ISC. */
    val Dices = arrayOf(
            "M4,10h8a2,2 0 0 1 2,2v8a2,2 0 0 1 -2,2h-8a2,2 0 0 1 -2,-2v-8a2,2 0 0 1 2,-2z",
            "m17.92 14 3.5-3.5a2.24 2.24 0 0 0 0-3l-5-4.92a2.24 2.24 0 0 0-3 0L10 6",
            "M6 18h.01",
            "M10 14h.01",
            "M15 6h.01",
            "M18 9h.01",
    )

    /** Lucide star @ 0.446.0, ISC. */
    val Star = arrayOf(
            "M12,2L15.09,8.26L22,9.27L17,14.14L18.18,21.02L12,17.77L5.82,21.02L7,14.14L2,9.27L8.91,8.26L12,2Z",
    )

    /** Lucide ticket @ 0.446.0, ISC. */
    val Ticket = arrayOf(
            "M2 9a3 3 0 0 1 0 6v2a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-2a3 3 0 0 1 0-6V7a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2Z",
            "M13 5v2",
            "M13 17v2",
            "M13 11v2",
    )

    /** Lucide clock @ 0.446.0, ISC. */
    val Clock = arrayOf(
            "M22,12A10,10 0 1 1 2,12A10,10 0 1 1 22,12",
            "M12,6L12,12L16,14",
    )

    /** Lucide layout-grid @ 0.446.0, ISC. */
    val LayoutGrid = arrayOf(
            "M4,3h5a1,1 0 0 1 1,1v5a1,1 0 0 1 -1,1h-5a1,1 0 0 1 -1,-1v-5a1,1 0 0 1 1,-1z",
            "M15,3h5a1,1 0 0 1 1,1v5a1,1 0 0 1 -1,1h-5a1,1 0 0 1 -1,-1v-5a1,1 0 0 1 1,-1z",
            "M15,14h5a1,1 0 0 1 1,1v5a1,1 0 0 1 -1,1h-5a1,1 0 0 1 -1,-1v-5a1,1 0 0 1 1,-1z",
            "M4,14h5a1,1 0 0 1 1,1v5a1,1 0 0 1 -1,1h-5a1,1 0 0 1 -1,-1v-5a1,1 0 0 1 1,-1z",
    )

    /** Lucide user @ 0.446.0, ISC. */
    val User = arrayOf(
            "M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2",
            "M16,7A4,4 0 1 1 8,7A4,4 0 1 1 16,7",
    )

    /** Lucide mail @ 0.446.0, ISC. */
    val Mail = arrayOf(
            "M4,4h16a2,2 0 0 1 2,2v12a2,2 0 0 1 -2,2h-16a2,2 0 0 1 -2,-2v-12a2,2 0 0 1 2,-2z",
            "m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7",
    )

    /** Lucide wallet @ 0.446.0, ISC. */
    val Wallet = arrayOf(
            "M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1",
            "M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4",
    )

    /** Lucide sparkles @ 0.446.0, ISC. */
    val Sparkles = arrayOf(
            "M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z",
            "M20 3v4",
            "M22 5h-4",
            "M4 17v2",
            "M5 18H3",
    )

    /** Lucide headphones @ 0.446.0, ISC. */
    val Headphones = arrayOf(
            "M3 14h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-7a9 9 0 0 1 18 0v7a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3",
    )

    /** Lucide shield-check @ 0.446.0, ISC. */
    val ShieldCheck = arrayOf(
            "M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z",
            "m9 12 2 2 4-4",
    )

    /** Lucide zap @ 0.446.0, ISC. */
    val Zap = arrayOf(
            "M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z",
    )

    /** Lucide video @ 0.446.0, ISC. */
    val Video = arrayOf(
            "m16 13 5.223 3.482a.5.5 0 0 0 .777-.416V7.87a.5.5 0 0 0-.752-.432L16 10.5",
            "M4,6h10a2,2 0 0 1 2,2v8a2,2 0 0 1 -2,2h-10a2,2 0 0 1 -2,-2v-8a2,2 0 0 1 2,-2z",
    )

    /** Lucide check-circle @ 0.446.0, ISC. */
    val CheckCircle = arrayOf(
            "M21.801 10A10 10 0 1 1 17 3.335",
            "m9 11 3 3L22 4",
    )

    /** Lucide flag @ 0.446.0, ISC. */
    val Flag = arrayOf(
            "M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z",
            "M4,22L4,15",
    )

    /** Lucide heart @ 0.446.0, ISC. */
    val Heart = arrayOf(
            "M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z",
    )

    /** Lucide gift @ 0.446.0, ISC. */
    val Gift = arrayOf(
            "M4,8h16a1,1 0 0 1 1,1v2a1,1 0 0 1 -1,1h-16a1,1 0 0 1 -1,-1v-2a1,1 0 0 1 1,-1z",
            "M12 8v13",
            "M19 12v7a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2v-7",
            "M7.5 8a2.5 2.5 0 0 1 0-5A4.8 8 0 0 1 12 8a4.8 8 0 0 1 4.5-5 2.5 2.5 0 0 1 0 5",
    )

    /** Lucide boxes @ 0.446.0, ISC. */
    val Boxes = arrayOf(
            "M2.97 12.92A2 2 0 0 0 2 14.63v3.24a2 2 0 0 0 .97 1.71l3 1.8a2 2 0 0 0 2.06 0L12 19v-5.5l-5-3-4.03 2.42Z",
            "m7 16.5-4.74-2.85",
            "m7 16.5 5-3",
            "M7 16.5v5.17",
            "M12 13.5V19l3.97 2.38a2 2 0 0 0 2.06 0l3-1.8a2 2 0 0 0 .97-1.71v-3.24a2 2 0 0 0-.97-1.71L17 10.5l-5 3Z",
            "m17 16.5-5-3",
            "m17 16.5 4.74-2.85",
            "M17 16.5v5.17",
            "M7.97 4.42A2 2 0 0 0 7 6.13v4.37l5 3 5-3V6.13a2 2 0 0 0-.97-1.71l-3-1.8a2 2 0 0 0-2.06 0l-3 1.8Z",
            "M12 8 7.26 5.15",
            "m12 8 4.74-2.85",
            "M12 13.5V8",
    )

    /** Lucide key-round @ 0.446.0, ISC. */
    val KeyRound = arrayOf(
            "M2.586 17.414A2 2 0 0 0 2 18.828V21a1 1 0 0 0 1 1h3a1 1 0 0 0 1-1v-1a1 1 0 0 1 1-1h1a1 1 0 0 0 1-1v-1a1 1 0 0 1 1-1h.172a2 2 0 0 0 1.414-.586l.814-.814a6.5 6.5 0 1 0-4-4z",
            "M17,7.5A0.5,0.5 0 1 1 16,7.5A0.5,0.5 0 1 1 17,7.5",
    )

    /** Lucide target @ 0.446.0, ISC. */
    val Target = arrayOf(
            "M22,12A10,10 0 1 1 2,12A10,10 0 1 1 22,12",
            "M18,12A6,6 0 1 1 6,12A6,6 0 1 1 18,12",
            "M14,12A2,2 0 1 1 10,12A2,2 0 1 1 14,12",
    )

    /** Lucide trending-up @ 0.446.0, ISC. */
    val TrendingUp = arrayOf(
            "M22,7L13.5,15.5L8.5,10.5L2,17",
            "M16,7L22,7L22,13",
    )

    /** Lucide wrench @ 0.446.0, ISC. */
    val Wrench = arrayOf(
            "M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z",
    )

    /** Lucide scan-line @ 0.446.0, ISC. */
    val ScanLine = arrayOf(
            "M3 7V5a2 2 0 0 1 2-2h2",
            "M17 3h2a2 2 0 0 1 2 2v2",
            "M21 17v2a2 2 0 0 1-2 2h-2",
            "M7 21H5a2 2 0 0 1-2-2v-2",
            "M7 12h10",
    )

    /** Lucide bell @ 0.446.0, ISC. */
    val Bell = arrayOf(
            "M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9",
            "M10.3 21a1.94 1.94 0 0 0 3.4 0",
    )

    /** Lucide info @ 0.446.0, ISC. */
    val Info = arrayOf(
            "M22,12A10,10 0 1 1 2,12A10,10 0 1 1 22,12",
            "M12 16v-4",
            "M12 8h.01",
    )

    /** Lucide log-out @ 0.446.0, ISC. */
    val LogOut = arrayOf(
            "M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4",
            "M16,17L21,12L16,7",
            "M21,12L9,12",
    )

    /** Lucide x @ 0.446.0, ISC. */
    val X = arrayOf(
            "M18 6 6 18",
            "m6 6 12 12",
    )

    /** Lucide pin @ 0.446.0, ISC. */
    val Pin = arrayOf(
            "M12 17v5",
            "M9 10.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24V16a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-.76a2 2 0 0 0-1.11-1.79l-1.78-.9A2 2 0 0 1 15 10.76V7a1 1 0 0 1 1-1 2 2 0 0 0 0-4H8a2 2 0 0 0 0 4 1 1 0 0 1 1 1z",
    )

    /** Lucide radio @ 0.446.0, ISC. */
    val Radio = arrayOf(
            "M4.9 19.1C1 15.2 1 8.8 4.9 4.9",
            "M7.8 16.2c-2.3-2.3-2.3-6.1 0-8.5",
            "M14,12A2,2 0 1 1 10,12A2,2 0 1 1 14,12",
            "M16.2 7.8c2.3 2.3 2.3 6.1 0 8.5",
            "M19.1 4.9C23 8.8 23 15.1 19.1 19",
    )

    /** Lucide play @ 0.446.0, ISC. */
    val Play = arrayOf(
            "M6,3L20,12L6,21L6,3Z",
    )

    /** Lucide lock @ 0.446.0, ISC. */
    val Lock = arrayOf(
            "M5,11h14a2,2 0 0 1 2,2v7a2,2 0 0 1 -2,2h-14a2,2 0 0 1 -2,-2v-7a2,2 0 0 1 2,-2z",
            "M7 11V7a5 5 0 0 1 10 0v4",
    )

    /** Lucide eye @ 0.446.0, ISC. */
    val Eye = arrayOf(
            "M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0",
            "M15,12A3,3 0 1 1 9,12A3,3 0 1 1 15,12",
    )

    /** Lucide eye-off @ 0.446.0, ISC. */
    val EyeOff = arrayOf(
            "M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49",
            "M14.084 14.158a3 3 0 0 1-4.242-4.242",
            "M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143",
            "m2 2 20 20",
    )

    /** Lucide phone @ 0.446.0, ISC. */
    val Phone = arrayOf(
            "M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z",
    )

    /** Lucide smartphone @ 0.446.0, ISC. */
    val Smartphone = arrayOf(
            "M7,2h10a2,2 0 0 1 2,2v16a2,2 0 0 1 -2,2h-10a2,2 0 0 1 -2,-2v-16a2,2 0 0 1 2,-2z",
            "M12 18h.01",
    )

    /** Lucide copy @ 0.446.0, ISC. */
    val Copy = arrayOf(
            "M10,8h10a2,2 0 0 1 2,2v10a2,2 0 0 1 -2,2h-10a2,2 0 0 1 -2,-2v-10a2,2 0 0 1 2,-2z",
            "M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2",
    )

    /** Lucide calendar @ 0.446.0, ISC. */
    val Calendar = arrayOf(
            "M8 2v4",
            "M16 2v4",
            "M5,4h14a2,2 0 0 1 2,2v14a2,2 0 0 1 -2,2h-14a2,2 0 0 1 -2,-2v-14a2,2 0 0 1 2,-2z",
            "M3 10h18",
    )

    /** Lucide tag @ 0.446.0, ISC. */
    val Tag = arrayOf(
            "M12.586 2.586A2 2 0 0 0 11.172 2H4a2 2 0 0 0-2 2v7.172a2 2 0 0 0 .586 1.414l8.704 8.704a2.426 2.426 0 0 0 3.42 0l6.58-6.58a2.426 2.426 0 0 0 0-3.42z",
            "M8,7.5A0.5,0.5 0 1 1 7,7.5A0.5,0.5 0 1 1 8,7.5",
    )

    /** Lucide globe @ 0.446.0, ISC. */
    val Globe = arrayOf(
            "M22,12A10,10 0 1 1 2,12A10,10 0 1 1 22,12",
            "M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20",
            "M2 12h20",
    )

    /** Lucide tv @ 0.446.0, ISC. */
    val Tv = arrayOf(
            "M4,7h16a2,2 0 0 1 2,2v11a2,2 0 0 1 -2,2h-16a2,2 0 0 1 -2,-2v-11a2,2 0 0 1 2,-2z",
            "M17,2L12,7L7,2",
    )

    /** Lucide arrow-left @ 0.446.0, ISC. */
    val ArrowLeft = arrayOf(
            "m12 19-7-7 7-7",
            "M19 12H5",
    )

    /** Lucide check @ 0.446.0, ISC. */
    val Check = arrayOf(
            "M20 6 9 17l-5-5",
    )

    /** Lucide minus @ 0.446.0, ISC. */
    val Minus = arrayOf(
            "M5 12h14",
    )

    /** Lucide layers @ 0.446.0, ISC. */
    val Layers = arrayOf(
            "m12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83Z",
            "m22 17.65-9.17 4.16a2 2 0 0 1-1.66 0L2 17.65",
            "m22 12.65-9.17 4.16a2 2 0 0 1-1.66 0L2 12.65",
    )

    /** Lucide alert-triangle @ 0.446.0, ISC. */
    val AlertTriangle = arrayOf(
            "m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3",
            "M12 9v4",
            "M12 17h.01",
    )

    /** Lucide trash-2 @ 0.446.0, ISC. */
    val Trash2 = arrayOf(
            "M3 6h18",
            "M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6",
            "M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2",
            "M10,11L10,17",
            "M14,11L14,17",
    )

    /** Lucide arrow-down-to-line @ 0.446.0, ISC. */
    val ArrowDownToLine = arrayOf(
            "M12 17V3",
            "m6 11 6 6 6-6",
            "M19 21H5",
    )

    /** Lucide arrow-up-from-line @ 0.446.0, ISC. */
    val ArrowUpFromLine = arrayOf(
            "m18 9-6-6-6 6",
            "M12 3v14",
            "M5 21h14",
    )

    /** Lucide clipboard-check @ 0.446.0, ISC. */
    val ClipboardCheck = arrayOf(
            "M9,2h6a1,1 0 0 1 1,1v2a1,1 0 0 1 -1,1h-6a1,1 0 0 1 -1,-1v-2a1,1 0 0 1 1,-1z",
            "M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2",
            "m9 14 2 2 4-4",
    )

    /** Lucide mouse-pointer-click @ 0.446.0, ISC. */
    val MousePointerClick = arrayOf(
            "M14 4.1 12 6",
            "m5.1 8-2.9-.8",
            "m6 12-1.9 2",
            "M7.2 2.2 8 5.1",
            "M9.037 9.69a.498.498 0 0 1 .653-.653l11 4.5a.5.5 0 0 1-.074.949l-4.349 1.041a1 1 0 0 0-.74.739l-1.04 4.35a.5.5 0 0 1-.95.074z",
    )

    /** Lucide percent @ 0.446.0, ISC. */
    val Percent = arrayOf(
            "M19,5L5,19",
            "M9,6.5A2.5,2.5 0 1 1 4,6.5A2.5,2.5 0 1 1 9,6.5",
            "M20,17.5A2.5,2.5 0 1 1 15,17.5A2.5,2.5 0 1 1 20,17.5",
    )

    /** Lucide share-2 @ 0.446.0, ISC. */
    val Share2 = arrayOf(
            "M21,5A3,3 0 1 1 15,5A3,3 0 1 1 21,5",
            "M9,12A3,3 0 1 1 3,12A3,3 0 1 1 9,12",
            "M21,19A3,3 0 1 1 15,19A3,3 0 1 1 21,19",
            "M8.59,13.51L15.42,17.49",
            "M15.41,6.51L8.59,10.49",
    )

    /** Lucide check-circle-2 @ 0.446.0, ISC. */
    val CheckCircle2 = arrayOf(
            "M22,12A10,10 0 1 1 2,12A10,10 0 1 1 22,12",
            "m9 12 2 2 4-4",
    )

    /** Lucide clock-3 @ 0.446.0, ISC. */
    val Clock3 = arrayOf(
            "M22,12A10,10 0 1 1 2,12A10,10 0 1 1 22,12",
            "M12,6L12,12L16.5,12",
    )

    /** Lucide x-circle @ 0.446.0, ISC. */
    val XCircle = arrayOf(
            "M22,12A10,10 0 1 1 2,12A10,10 0 1 1 22,12",
            "m15 9-6 6",
            "m9 9 6 6",
    )

    /** Lucide bitcoin @ 0.446.0, ISC. */
    val Bitcoin = arrayOf(
            "M11.767 19.089c4.924.868 6.14-6.025 1.216-6.894m-1.216 6.894L5.86 18.047m5.908 1.042-.347 1.97m1.563-8.864c4.924.869 6.14-6.025 1.215-6.893m-1.215 6.893-3.94-.694m5.155-6.2L8.29 4.26m5.908 1.042.348-1.97M7.48 20.364l3.126-17.727",
    )

    /** Lucide banknote @ 0.446.0, ISC. */
    val Banknote = arrayOf(
            "M4,6h16a2,2 0 0 1 2,2v8a2,2 0 0 1 -2,2h-16a2,2 0 0 1 -2,-2v-8a2,2 0 0 1 2,-2z",
            "M14,12A2,2 0 1 1 10,12A2,2 0 1 1 14,12",
            "M6 12h.01M18 12h.01",
    )

    /** Lucide map-pin @ 0.446.0, ISC. */
    val MapPin = arrayOf(
            "M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0",
            "M15,10A3,3 0 1 1 9,10A3,3 0 1 1 15,10",
    )

    /** Lucide building-2 @ 0.446.0, ISC. */
    val Building2 = arrayOf(
            "M6 22V4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v18Z",
            "M6 12H4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h2",
            "M18 9h2a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2h-2",
            "M10 6h4",
            "M10 10h4",
            "M10 14h4",
            "M10 18h4",
    )

    /** Lucide scale @ 0.446.0, ISC. */
    val Scale = arrayOf(
            "m16 16 3-8 3 8c-.87.65-1.92 1-3 1s-2.13-.35-3-1Z",
            "m2 16 3-8 3 8c-.87.65-1.92 1-3 1s-2.13-.35-3-1Z",
            "M7 21h10",
            "M12 3v18",
            "M3 7h2c2 0 5-1 7-2 2 1 5 2 7 2h2",
    )

    /** Lucide credit-card @ 0.446.0, ISC. */
    val CreditCard = arrayOf(
            "M4,5h16a2,2 0 0 1 2,2v10a2,2 0 0 1 -2,2h-16a2,2 0 0 1 -2,-2v-10a2,2 0 0 1 2,-2z",
            "M2,10L22,10",
    )

    /** Lucide book-open @ 0.446.0, ISC. */
    val BookOpen = arrayOf(
            "M12 7v14",
            "M3 18a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h5a4 4 0 0 1 4 4 4 4 0 0 1 4-4h5a1 1 0 0 1 1 1v13a1 1 0 0 1-1 1h-6a3 3 0 0 0-3 3 3 3 0 0 0-3-3z",
    )

    /** Lucide shopping-cart @ 0.446.0, ISC. */
    val ShoppingCart = arrayOf(
            "M9,21A1,1 0 1 1 7,21A1,1 0 1 1 9,21",
            "M20,21A1,1 0 1 1 18,21A1,1 0 1 1 20,21",
            "M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12",
    )

    /** Lucide rotate-ccw @ 0.446.0, ISC. */
    val RotateCcw = arrayOf(
            "M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8",
            "M3 3v5h5",
    )

    /** Lucide award @ 0.446.0, ISC. */
    val Award = arrayOf(
            "m15.477 12.89 1.515 8.526a.5.5 0 0 1-.81.47l-3.58-2.687a1 1 0 0 0-1.197 0l-3.586 2.686a.5.5 0 0 1-.81-.469l1.514-8.526",
            "M18,8A6,6 0 1 1 6,8A6,6 0 1 1 18,8",
    )

    /** Lucide circle-dollar-sign @ 0.446.0, ISC. */
    val CircleDollarSign = arrayOf(
            "M22,12A10,10 0 1 1 2,12A10,10 0 1 1 22,12",
            "M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8",
            "M12 18V6",
    )

    /** Lucide coins @ 0.446.0, ISC. */
    val Coins = arrayOf(
            "M14,8A6,6 0 1 1 2,8A6,6 0 1 1 14,8",
            "M18.09 10.37A6 6 0 1 1 10.34 18",
            "M7 6h1v4",
            "m16.71 13.88.7.71-2.82 2.82",
    )

    /** Lucide crown @ 0.446.0, ISC. */
    val Crown = arrayOf(
            "M11.562 3.266a.5.5 0 0 1 .876 0L15.39 8.87a1 1 0 0 0 1.516.294L21.183 5.5a.5.5 0 0 1 .798.519l-2.834 10.246a1 1 0 0 1-.956.734H5.81a1 1 0 0 1-.957-.734L2.02 6.02a.5.5 0 0 1 .798-.519l4.276 3.664a1 1 0 0 0 1.516-.294z",
            "M5 21h14",
    )

    /** Lucide gem @ 0.446.0, ISC. */
    val Gem = arrayOf(
            "M6 3h12l4 6-10 13L2 9Z",
            "M11 3 8 9l4 13 4-13-3-6",
            "M2 9h20",
    )

    /** Lucide save @ 0.446.0, ISC. */
    val Save = arrayOf(
            "M15.2 3a2 2 0 0 1 1.4.6l3.8 3.8a2 2 0 0 1 .6 1.4V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2z",
            "M17 21v-7a1 1 0 0 0-1-1H8a1 1 0 0 0-1 1v7",
            "M7 3v4a1 1 0 0 0 1 1h7",
    )

    /** Lucide more-vertical @ 0.446.0, ISC. */
    val MoreVertical = arrayOf(
            "M13,12A1,1 0 1 1 11,12A1,1 0 1 1 13,12",
            "M13,5A1,1 0 1 1 11,5A1,1 0 1 1 13,5",
            "M13,19A1,1 0 1 1 11,19A1,1 0 1 1 13,19",
    )

    /** Lucide sliders-horizontal @ 0.446.0, ISC. */
    val SlidersHorizontal = arrayOf(
            "M21,4L14,4",
            "M10,4L3,4",
            "M21,12L12,12",
            "M8,12L3,12",
            "M21,20L16,20",
            "M12,20L3,20",
            "M14,2L14,6",
            "M8,10L8,14",
            "M16,18L16,22",
    )

    /** Lucide settings-2 @ 0.446.0, ISC. */
    val Settings2 = arrayOf(
            "M20 7h-9",
            "M14 17H5",
            "M20,17A3,3 0 1 1 14,17A3,3 0 1 1 20,17",
            "M10,7A3,3 0 1 1 4,7A3,3 0 1 1 10,7",
    )

    /** Lucide refresh-cw @ 0.446.0, ISC. */
    val RefreshCw = arrayOf(
            "M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8",
            "M21 3v5h-5",
            "M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16",
            "M8 16H3v5",
    )

    /** Lucide expand @ 0.446.0, ISC. */
    val Expand = arrayOf(
            "m21 21-6-6m6 6v-4.8m0 4.8h-4.8",
            "M3 16.2V21m0 0h4.8M3 21l6-6",
            "M21 7.8V3m0 0h-4.8M21 3l-6 6",
            "M3 7.8V3m0 0h4.8M3 3l6 6",
    )

    /** Lucide filter @ 0.446.0, ISC. */
    val Filter = arrayOf(
            "M22,3L2,3L10,12.46L10,19L14,21L14,12.46L22,3Z",
    )

    /** Lucide wifi @ 0.446.0, ISC. */
    val Wifi = arrayOf(
            "M12 20h.01",
            "M2 8.82a15 15 0 0 1 20 0",
            "M5 12.859a10 10 0 0 1 14 0",
            "M8.5 16.429a5 5 0 0 1 7 0",
    )

}

object NextpariWebIcons {
    const val DefaultStroke = 2f
    const val HeaderPlusStroke = 2.5f
    const val HeaderStroke = 2.2f
    const val MainTabsStroke = 1.75f
    const val BottomNavActiveStroke = 2.4f
    const val BottomNavInactiveStroke = 2f
    const val CouponStroke = 2.4f
    const val MenuStroke = 1.5f

    val TabActive = Color(0xFFC88D3E)
    val TabInactiveLight = Color(0xFF9CA3AF)
    val TabInactiveDark = Color(0xFF6B7280)
    val MenuGreen = Color(0xFF4ADE80)
    val LiveRed = Color(0xFFEF4444)
    val HeaderLight = Color(0xFF1F2937)
    val HeaderDark = Color(0xFFE5E7EB)

    private val cache = ConcurrentHashMap<String, ImageVector>()

    fun vector(name: String, paths: Array<String>, strokeWidth: Float): ImageVector {
        val key = name + "@" + strokeWidth
        return cache.getOrPut(key) {
            val builder = ImageVector.Builder(
                name = "lucide." + name,
                defaultWidth = 24.dp,
                defaultHeight = 24.dp,
                viewportWidth = 24f,
                viewportHeight = 24f,
            )
            val parser = PathParser()
            paths.forEach { d ->
                builder.addPath(
                    pathData = parser.parsePathString(d).toNodes().toList(),
                    fill = SolidColor(Color.Transparent),
                    fillAlpha = 0f,
                    stroke = SolidColor(Color.Black),
                    strokeLineWidth = strokeWidth,
                    strokeLineCap = StrokeCap.Round,
                    strokeLineJoin = StrokeJoin.Round,
                    strokeLineMiter = 4f,
                )
                parser.clear()
            }
            builder.build()
        }
    }

    fun plus(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Plus", NextpariLucideGeometry.Plus, strokeWidth)

    val Plus: ImageVector get() = plus()

    fun moon(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Moon", NextpariLucideGeometry.Moon, strokeWidth)

    val Moon: ImageVector get() = moon()

    fun sun(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Sun", NextpariLucideGeometry.Sun, strokeWidth)

    val Sun: ImageVector get() = sun()

    fun settings(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Settings", NextpariLucideGeometry.Settings, strokeWidth)

    val Settings: ImageVector get() = settings()

    fun search(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Search", NextpariLucideGeometry.Search, strokeWidth)

    val Search: ImageVector get() = search()

    fun chevronDown(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("ChevronDown", NextpariLucideGeometry.ChevronDown, strokeWidth)

    val ChevronDown: ImageVector get() = chevronDown()

    fun chevronRight(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("ChevronRight", NextpariLucideGeometry.ChevronRight, strokeWidth)

    val ChevronRight: ImageVector get() = chevronRight()

    fun chevronLeft(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("ChevronLeft", NextpariLucideGeometry.ChevronLeft, strokeWidth)

    val ChevronLeft: ImageVector get() = chevronLeft()

    fun chevronUp(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("ChevronUp", NextpariLucideGeometry.ChevronUp, strokeWidth)

    val ChevronUp: ImageVector get() = chevronUp()

    fun flame(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Flame", NextpariLucideGeometry.Flame, strokeWidth)

    val Flame: ImageVector get() = flame()

    fun trophy(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Trophy", NextpariLucideGeometry.Trophy, strokeWidth)

    val Trophy: ImageVector get() = trophy()

    fun gamepad2(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Gamepad2", NextpariLucideGeometry.Gamepad2, strokeWidth)

    val Gamepad2: ImageVector get() = gamepad2()

    fun dices(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Dices", NextpariLucideGeometry.Dices, strokeWidth)

    val Dices: ImageVector get() = dices()

    fun star(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Star", NextpariLucideGeometry.Star, strokeWidth)

    val Star: ImageVector get() = star()

    fun ticket(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Ticket", NextpariLucideGeometry.Ticket, strokeWidth)

    val Ticket: ImageVector get() = ticket()

    fun clock(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Clock", NextpariLucideGeometry.Clock, strokeWidth)

    val Clock: ImageVector get() = clock()

    fun layoutGrid(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("LayoutGrid", NextpariLucideGeometry.LayoutGrid, strokeWidth)

    val LayoutGrid: ImageVector get() = layoutGrid()

    fun user(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("User", NextpariLucideGeometry.User, strokeWidth)

    val User: ImageVector get() = user()

    fun mail(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Mail", NextpariLucideGeometry.Mail, strokeWidth)

    val Mail: ImageVector get() = mail()

    fun wallet(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Wallet", NextpariLucideGeometry.Wallet, strokeWidth)

    val Wallet: ImageVector get() = wallet()

    fun sparkles(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Sparkles", NextpariLucideGeometry.Sparkles, strokeWidth)

    val Sparkles: ImageVector get() = sparkles()

    fun headphones(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Headphones", NextpariLucideGeometry.Headphones, strokeWidth)

    val Headphones: ImageVector get() = headphones()

    fun shieldCheck(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("ShieldCheck", NextpariLucideGeometry.ShieldCheck, strokeWidth)

    val ShieldCheck: ImageVector get() = shieldCheck()

    fun zap(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Zap", NextpariLucideGeometry.Zap, strokeWidth)

    val Zap: ImageVector get() = zap()

    fun video(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Video", NextpariLucideGeometry.Video, strokeWidth)

    val Video: ImageVector get() = video()

    fun checkCircle(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("CheckCircle", NextpariLucideGeometry.CheckCircle, strokeWidth)

    val CheckCircle: ImageVector get() = checkCircle()

    fun flag(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Flag", NextpariLucideGeometry.Flag, strokeWidth)

    val Flag: ImageVector get() = flag()

    fun heart(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Heart", NextpariLucideGeometry.Heart, strokeWidth)

    val Heart: ImageVector get() = heart()

    fun gift(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Gift", NextpariLucideGeometry.Gift, strokeWidth)

    val Gift: ImageVector get() = gift()

    fun boxes(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Boxes", NextpariLucideGeometry.Boxes, strokeWidth)

    val Boxes: ImageVector get() = boxes()

    fun keyRound(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("KeyRound", NextpariLucideGeometry.KeyRound, strokeWidth)

    val KeyRound: ImageVector get() = keyRound()

    fun target(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Target", NextpariLucideGeometry.Target, strokeWidth)

    val Target: ImageVector get() = target()

    fun trendingUp(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("TrendingUp", NextpariLucideGeometry.TrendingUp, strokeWidth)

    val TrendingUp: ImageVector get() = trendingUp()

    fun wrench(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Wrench", NextpariLucideGeometry.Wrench, strokeWidth)

    val Wrench: ImageVector get() = wrench()

    fun scanLine(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("ScanLine", NextpariLucideGeometry.ScanLine, strokeWidth)

    val ScanLine: ImageVector get() = scanLine()

    fun bell(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Bell", NextpariLucideGeometry.Bell, strokeWidth)

    val Bell: ImageVector get() = bell()

    fun info(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Info", NextpariLucideGeometry.Info, strokeWidth)

    val Info: ImageVector get() = info()

    fun logOut(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("LogOut", NextpariLucideGeometry.LogOut, strokeWidth)

    val LogOut: ImageVector get() = logOut()

    fun x(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("X", NextpariLucideGeometry.X, strokeWidth)

    val X: ImageVector get() = x()

    fun pin(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Pin", NextpariLucideGeometry.Pin, strokeWidth)

    val Pin: ImageVector get() = pin()

    fun radio(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Radio", NextpariLucideGeometry.Radio, strokeWidth)

    val Radio: ImageVector get() = radio()

    fun play(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Play", NextpariLucideGeometry.Play, strokeWidth)

    val Play: ImageVector get() = play()

    fun lock(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Lock", NextpariLucideGeometry.Lock, strokeWidth)

    val Lock: ImageVector get() = lock()

    fun eye(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Eye", NextpariLucideGeometry.Eye, strokeWidth)

    val Eye: ImageVector get() = eye()

    fun eyeOff(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("EyeOff", NextpariLucideGeometry.EyeOff, strokeWidth)

    val EyeOff: ImageVector get() = eyeOff()

    fun phone(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Phone", NextpariLucideGeometry.Phone, strokeWidth)

    val Phone: ImageVector get() = phone()

    fun smartphone(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Smartphone", NextpariLucideGeometry.Smartphone, strokeWidth)

    val Smartphone: ImageVector get() = smartphone()

    fun copy(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Copy", NextpariLucideGeometry.Copy, strokeWidth)

    val Copy: ImageVector get() = copy()

    fun calendar(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Calendar", NextpariLucideGeometry.Calendar, strokeWidth)

    val Calendar: ImageVector get() = calendar()

    fun tag(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Tag", NextpariLucideGeometry.Tag, strokeWidth)

    val Tag: ImageVector get() = tag()

    fun globe(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Globe", NextpariLucideGeometry.Globe, strokeWidth)

    val Globe: ImageVector get() = globe()

    fun tv(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Tv", NextpariLucideGeometry.Tv, strokeWidth)

    val Tv: ImageVector get() = tv()

    fun arrowLeft(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("ArrowLeft", NextpariLucideGeometry.ArrowLeft, strokeWidth)

    val ArrowLeft: ImageVector get() = arrowLeft()

    fun check(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Check", NextpariLucideGeometry.Check, strokeWidth)

    val Check: ImageVector get() = check()

    fun minus(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Minus", NextpariLucideGeometry.Minus, strokeWidth)

    val Minus: ImageVector get() = minus()

    fun layers(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Layers", NextpariLucideGeometry.Layers, strokeWidth)

    val Layers: ImageVector get() = layers()

    fun alertTriangle(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("AlertTriangle", NextpariLucideGeometry.AlertTriangle, strokeWidth)

    val AlertTriangle: ImageVector get() = alertTriangle()

    fun trash2(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Trash2", NextpariLucideGeometry.Trash2, strokeWidth)

    val Trash2: ImageVector get() = trash2()

    fun arrowDownToLine(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("ArrowDownToLine", NextpariLucideGeometry.ArrowDownToLine, strokeWidth)

    val ArrowDownToLine: ImageVector get() = arrowDownToLine()

    fun arrowUpFromLine(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("ArrowUpFromLine", NextpariLucideGeometry.ArrowUpFromLine, strokeWidth)

    val ArrowUpFromLine: ImageVector get() = arrowUpFromLine()

    fun clipboardCheck(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("ClipboardCheck", NextpariLucideGeometry.ClipboardCheck, strokeWidth)

    val ClipboardCheck: ImageVector get() = clipboardCheck()

    fun mousePointerClick(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("MousePointerClick", NextpariLucideGeometry.MousePointerClick, strokeWidth)

    val MousePointerClick: ImageVector get() = mousePointerClick()

    fun percent(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Percent", NextpariLucideGeometry.Percent, strokeWidth)

    val Percent: ImageVector get() = percent()

    fun share2(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Share2", NextpariLucideGeometry.Share2, strokeWidth)

    val Share2: ImageVector get() = share2()

    fun checkCircle2(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("CheckCircle2", NextpariLucideGeometry.CheckCircle2, strokeWidth)

    val CheckCircle2: ImageVector get() = checkCircle2()

    fun clock3(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Clock3", NextpariLucideGeometry.Clock3, strokeWidth)

    val Clock3: ImageVector get() = clock3()

    fun xCircle(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("XCircle", NextpariLucideGeometry.XCircle, strokeWidth)

    val XCircle: ImageVector get() = xCircle()

    fun bitcoin(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Bitcoin", NextpariLucideGeometry.Bitcoin, strokeWidth)

    val Bitcoin: ImageVector get() = bitcoin()

    fun banknote(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Banknote", NextpariLucideGeometry.Banknote, strokeWidth)

    val Banknote: ImageVector get() = banknote()

    fun mapPin(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("MapPin", NextpariLucideGeometry.MapPin, strokeWidth)

    val MapPin: ImageVector get() = mapPin()

    fun building2(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Building2", NextpariLucideGeometry.Building2, strokeWidth)

    val Building2: ImageVector get() = building2()

    fun scale(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Scale", NextpariLucideGeometry.Scale, strokeWidth)

    val Scale: ImageVector get() = scale()

    fun creditCard(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("CreditCard", NextpariLucideGeometry.CreditCard, strokeWidth)

    val CreditCard: ImageVector get() = creditCard()

    fun bookOpen(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("BookOpen", NextpariLucideGeometry.BookOpen, strokeWidth)

    val BookOpen: ImageVector get() = bookOpen()

    fun shoppingCart(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("ShoppingCart", NextpariLucideGeometry.ShoppingCart, strokeWidth)

    val ShoppingCart: ImageVector get() = shoppingCart()

    fun rotateCcw(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("RotateCcw", NextpariLucideGeometry.RotateCcw, strokeWidth)

    val RotateCcw: ImageVector get() = rotateCcw()

    fun award(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Award", NextpariLucideGeometry.Award, strokeWidth)

    val Award: ImageVector get() = award()

    fun circleDollarSign(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("CircleDollarSign", NextpariLucideGeometry.CircleDollarSign, strokeWidth)

    val CircleDollarSign: ImageVector get() = circleDollarSign()

    fun coins(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Coins", NextpariLucideGeometry.Coins, strokeWidth)

    val Coins: ImageVector get() = coins()

    fun crown(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Crown", NextpariLucideGeometry.Crown, strokeWidth)

    val Crown: ImageVector get() = crown()

    fun gem(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Gem", NextpariLucideGeometry.Gem, strokeWidth)

    val Gem: ImageVector get() = gem()

    fun save(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Save", NextpariLucideGeometry.Save, strokeWidth)

    val Save: ImageVector get() = save()

    fun moreVertical(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("MoreVertical", NextpariLucideGeometry.MoreVertical, strokeWidth)

    val MoreVertical: ImageVector get() = moreVertical()

    fun slidersHorizontal(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("SlidersHorizontal", NextpariLucideGeometry.SlidersHorizontal, strokeWidth)

    val SlidersHorizontal: ImageVector get() = slidersHorizontal()

    fun settings2(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Settings2", NextpariLucideGeometry.Settings2, strokeWidth)

    val Settings2: ImageVector get() = settings2()

    fun refreshCw(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("RefreshCw", NextpariLucideGeometry.RefreshCw, strokeWidth)

    val RefreshCw: ImageVector get() = refreshCw()

    fun expand(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Expand", NextpariLucideGeometry.Expand, strokeWidth)

    val Expand: ImageVector get() = expand()

    fun filter(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Filter", NextpariLucideGeometry.Filter, strokeWidth)

    val Filter: ImageVector get() = filter()

    fun wifi(strokeWidth: Float = DefaultStroke): ImageVector =
        vector("Wifi", NextpariLucideGeometry.Wifi, strokeWidth)

    val Wifi: ImageVector get() = wifi()

}

@Composable
fun NextpariWebIcon(
    imageVector: ImageVector,
    contentDescription: String?,
    modifier: Modifier = Modifier,
    tint: Color = LocalContentColor.current,
) {
    Icon(
        imageVector = imageVector,
        contentDescription = contentDescription,
        modifier = modifier,
        tint = tint,
    )
}
