#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

THIS = Path(__file__).resolve()
ANDROID_DIR = THIS.parents[1]
REPO_ROOT = ANDROID_DIR.parent
PACK_ROOT = ANDROID_DIR / "design" / "nextpari_professional_icon_pack"
MAPPING_FILE = PACK_ROOT / "icon_mapping.json"
OUT_FILE = ANDROID_DIR / "app" / "src" / "main" / "java" / "com" / "nextpari" / "app" / "core" / "ui" / "icons" / "ProfessionalPremiumIcons.kt"

BASE = "https://raw.githubusercontent.com/phosphor-icons/core/main/assets/{weight}/{name}-{weight}.svg"

def fetch_svg(weight: str, name: str) -> str:
    url = BASE.format(weight=weight, name=name)
    req = urllib.request.Request(url, headers={"User-Agent": "Nextpari-Icon-Importer/1.0"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read().decode("utf-8")

def parse_svg(svg: str):
    root = ET.fromstring(svg)
    vb = root.attrib.get("viewBox", "0 0 256 256").split()
    if len(vb) != 4:
        raise ValueError(f"Unsupported viewBox: {vb}")
    _, _, vw, vh = map(float, vb)
    paths = []
    for elem in root.iter():
        tag = elem.tag.split("}")[-1]
        if tag == "path":
            d = elem.attrib.get("d")
            if d:
                paths.append(d)
    if not paths:
        raise ValueError("No path data found")
    return vw, vh, paths

def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")

def kotlin_prop(prop: str, weight: str, name: str, vw: float, vh: float, paths: list[str]) -> str:
    path_lines = []
    for d in paths:
        path_lines.append(
            '            addPath(\n'
            '                pathData = PathParser().parsePathString("' + esc(d) + '").toNodes(),\n'
            '                fill = SolidColor(Color.Black),\n'
            '            )'
        )
    path_code = "\n".join(path_lines)
    return (
        f'    /** Phosphor {name} ({weight}), MIT. */\n'
        f'    val {prop}: ImageVector by lazy {{\n'
        f'        ImageVector.Builder(\n'
        f'            name = "professional.{prop}",\n'
        f'            defaultWidth = 24.dp,\n'
        f'            defaultHeight = 24.dp,\n'
        f'            viewportWidth = {vw:g}f,\n'
        f'            viewportHeight = {vh:g}f,\n'
        f'        ).apply {{\n'
        f'{path_code}\n'
        f'        }}.build()\n'
        f'    }}\n'
    )

def main():
    if not MAPPING_FILE.exists():
        print(f"Missing mapping: {MAPPING_FILE}")
        sys.exit(2)

    mapping = json.loads(MAPPING_FILE.read_text(encoding="utf-8"))
    props = []
    failures = []

    for prop, spec in mapping.items():
        weight, name = spec
        print(f"[fetch] {prop}: {weight}/{name}")
        try:
            svg = fetch_svg(weight, name)
            vw, vh, paths = parse_svg(svg)
            props.append(kotlin_prop(prop, weight, name, vw, vh, paths))
        except Exception as e:
            failures.append((prop, weight, name, str(e)))

    if failures:
        print("\nFAILED:")
        for item in failures:
            print("  ", item)
        sys.exit(1)

    header = '''// AUTO-GENERATED by android/tools/import_nextpari_professional_icons.py
// Source: Phosphor Icons (MIT) — https://github.com/phosphor-icons/core
// Do not hand-edit. Change icon_mapping.json and rerun the importer.

package com.nextpari.app.core.ui.icons

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp

object ProfessionalPremiumIcons {
'''
    output = header + "\n".join(props) + "}\n"
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(output, encoding="utf-8")
    print(f"Generated: {OUT_FILE}")
    print(f"Icons: {len(props)}")

if __name__ == "__main__":
    main()
