import type { Sport, MatchEvent, CasinoGame, Transaction, MarketGroup, MatchStat, H2HGame, Championship, CasinoCategory, EsportsDiscipline, BetHistoryEntry } from './types';

const now = Date.now();

export const teamLogoMap: Record<string, string> = {
  'Манчестер Сити': '/crest1.webp',
  'Арсенал': '/crest2.webp',
  'Лейкерс': '/crest3.webp',
  'Бостон': '/crest4.webp',
  'Алькарас': '/crest5.webp',
  'Синнер': '/crest6.webp',
  'Реал Мадрид': '/crest7.webp',
  'Барселона': '/crest8.webp',
  'Рейнджерс': '/crest9.webp',
  'Питтсбург': '/crest10.webp',
  'NaVi': '/crest1.webp',
  'Vitality': '/crest2.webp',
  'ПСЖ': '/crest3.webp',
  'Бавария': '/crest4.webp',
  'Интер': '/crest5.webp',
  'Милан': '/crest6.webp',
  'Боруссия Д': '/crest7.webp',
  'Лейпциг': '/crest8.webp',
  'ЦСКА': '/crest9.webp',
  'Реал': '/crest7.webp',
  'Швёнтек': '/crest10.webp',
  'Сабаленка': '/crest1.webp',
  'Махачев': '/crest2.webp',
  'Топурия': '/crest3.webp',
  'СКА': '/crest4.webp',
  'Динамо М': '/crest5.webp',
  'Team Spirit': '/crest6.webp',
  'Gaimin Gladiators': '/crest7.webp',
  'Natus Vincere': '/crest1.webp',
  '3DMAX': '/crest8.webp',
  'Tundra': '/crest9.webp',
  'BetBoom': '/crest10.webp',
  'T1': '/crest2.webp',
  'Gen.G': '/crest7.webp',
  'FaZe': '/crest3.webp',
  'G2': '/crest4.webp',
  'LGD': '/crest5.webp',
  'Sentinels': '/crest6.webp',
  'LOUD': '/crest9.webp',
};

export const sports: Sport[] = [
  { id: 'all', name: 'Все', icon: 'Grid', color: '#4ade80' },
  { id: 'football', name: 'Футбол', icon: 'Circle', color: '#4ade80' },
  { id: 'tennis', name: 'Теннис', icon: 'Circle', color: '#4ade80' },
  { id: 'basketball', name: 'Баскетбол', icon: 'Circle', color: '#4ade80' },
  { id: 'hockey', name: 'Хоккей', icon: 'Circle', color: '#4ade80' },
  { id: 'volleyball', name: 'Волейбол', icon: 'Circle', color: '#4ade80' },
  { id: 'esports', name: 'КиберСпорт', icon: 'Gamepad', color: '#4ade80' },
  { id: 'table-tennis', name: 'Настольный теннис', icon: 'Circle', color: '#4ade80' },
  { id: 'badminton', name: 'Бадминтон', icon: 'Circle', color: '#4ade80' },
  { id: 'baseball', name: 'Бейсбол', icon: 'Circle', color: '#4ade80' },
  { id: 'polo', name: 'Поло', icon: 'Circle', color: '#4ade80' },
  { id: 'cricket', name: 'Крикет', icon: 'Circle', color: '#4ade80' },
  { id: 'beach-volleyball', name: 'Пляжный волейбол', icon: 'Circle', color: '#4ade80' },
  { id: 'snooker', name: 'Снукер', icon: 'Circle', color: '#4ade80' },
  { id: 'futsal', name: 'Футзал', icon: 'Circle', color: '#4ade80' },
  { id: 'elections', name: 'Выборы США', icon: 'Circle', color: '#4ade80' },
  { id: 'pickleball', name: 'Пиклбол', icon: 'Circle', color: '#4ade80' },
  { id: 'fifa', name: 'FIFA', icon: 'Gamepad', color: '#4ade80' },
  { id: 'mk', name: 'Mortal Kombat', icon: 'Circle', color: '#4ade80' },
  { id: 'polybet', name: 'Polybet', icon: 'Circle', color: '#4ade80' },
  { id: 'ufc', name: 'UFC', icon: 'Circle', color: '#4ade80' },
  { id: 'filter', name: 'Фильтр', icon: 'Sliders', color: '#4ade80' },
];

const commonStats: MatchStat[] = [
  { label: 'Атаки', team1: 42, team2: 38 },
  { label: 'Владение мячом', team1: '56%', team2: '44%' },
  { label: 'Удары в створ', team1: 5, team2: 3 },
  { label: 'Угловые', team1: 4, team2: 2 },
  { label: 'Жёлтые карточки', team1: 1, team2: 2 },
  { label: 'Фолы', team1: 8, team2: 11 },
];

const commonH2H: H2HGame[] = [
  { date: '15.09.25', result: 'Победа Манчестер Сити', score: '2:1' },
  { date: '03.04.25', result: 'Ничья', score: '1:1' },
  { date: '18.10.24', result: 'Победа Арсенала', score: '0:2' },
  { date: '22.05.24', result: 'Победа Манчестер Сити', score: '3:1' },
  { date: '11.01.24', result: 'Ничья', score: '2:2' },
];

function buildMarketGroups(m: { '1': number; x: number; '2': number }): MarketGroup[] {
  return [
    // === MAIN ===
    {
      id: '1x2',
      name: 'Основные исходы',
      category: 'main',
      layout: 'grid',
      outcomes: [
        { label: 'П1', odds: m['1'] },
        { label: 'X', odds: m.x },
        { label: 'П2', odds: m['2'] },
      ],
    },
    {
      id: 'double-chance',
      name: 'Двойной шанс',
      category: 'main',
      layout: 'grid',
      outcomes: [
        { label: '1X', odds: +(m['1'] * 0.65 + 1.1).toFixed(2) },
        { label: '12', odds: +(Math.min(m['1'], m['2']) * 0.7 + 1.05).toFixed(2) },
        { label: 'X2', odds: +(m['2'] * 0.65 + 1.1).toFixed(2) },
      ],
    },
    {
      id: 'btts',
      name: 'Обе забьют',
      category: 'main',
      layout: 'grid',
      outcomes: [
        { label: 'Да', odds: 1.65 },
        { label: 'Нет', odds: 2.15 },
      ],
    },
    // === TOTALS (under main) ===
    {
      id: 'total',
      name: 'Тотал матча',
      category: 'main',
      layout: 'table',
      outcomes: [
        { label: 'ТБ 0.5', odds: 1.08 },
        { label: 'ТМ 0.5', odds: 7.50 },
        { label: 'ТБ 1.5', odds: 1.45 },
        { label: 'ТМ 1.5', odds: 2.65 },
        { label: 'ТБ 2.5', odds: 2.10 },
        { label: 'ТМ 2.5', odds: 1.75 },
        { label: 'ТБ 3.5', odds: 3.40 },
        { label: 'ТМ 3.5', odds: 1.30 },
        { label: 'ТБ 4.5', odds: 6.20 },
        { label: 'ТМ 4.5', odds: 1.12 },
      ],
    },
    {
      id: 'asian-total',
      name: 'Азиатский тотал',
      category: 'main',
      layout: 'table',
      outcomes: [
        { label: 'ТБ 1.25', odds: 1.35 },
        { label: 'ТМ 1.25', odds: 3.10 },
        { label: 'ТБ 1.75', odds: 1.60 },
        { label: 'ТМ 1.75', odds: 2.30 },
        { label: 'ТБ 2.25', odds: 1.90 },
        { label: 'ТМ 2.25', odds: 1.85 },
        { label: 'ТБ 2.75', odds: 2.50 },
        { label: 'ТМ 2.75', odds: 1.50 },
        { label: 'ТБ 3.25', odds: 3.20 },
        { label: 'ТМ 3.25', odds: 1.32 },
      ],
    },
    {
      id: 'total-1',
      name: 'Тотал команды 1',
      category: 'main',
      layout: 'table',
      outcomes: [
        { label: 'ТБ1 0.5', odds: 1.20 },
        { label: 'ТМ1 0.5', odds: 4.50 },
        { label: 'ТБ1 1.5', odds: 1.85 },
        { label: 'ТМ1 1.5', odds: 1.95 },
        { label: 'ТБ1 2.5', odds: 3.20 },
        { label: 'ТМ1 2.5', odds: 1.33 },
      ],
    },
    {
      id: 'total-2',
      name: 'Тотал команды 2',
      category: 'main',
      layout: 'table',
      outcomes: [
        { label: 'ТБ2 0.5', odds: 1.25 },
        { label: 'ТМ2 0.5', odds: 3.80 },
        { label: 'ТБ2 1.5', odds: 2.10 },
        { label: 'ТМ2 1.5', odds: 1.72 },
        { label: 'ТБ2 2.5', odds: 3.80 },
        { label: 'ТМ2 2.5', odds: 1.25 },
      ],
    },
    // === HANDICAPS (under main) ===
    {
      id: 'handicap',
      name: 'Фора',
      category: 'main',
      layout: 'table',
      outcomes: [
        { label: 'Ф1 -1', odds: 2.25 },
        { label: 'Ф2 +1', odds: 1.65 },
        { label: 'Ф1 0', odds: 1.80 },
        { label: 'Ф2 0', odds: 2.00 },
        { label: 'Ф1 -1.5', odds: 2.80 },
        { label: 'Ф2 +1.5', odds: 1.40 },
        { label: 'Ф1 +1', odds: 1.35 },
        { label: 'Ф2 -1', odds: 3.20 },
        { label: 'Ф1 -2', odds: 3.50 },
        { label: 'Ф2 +2', odds: 1.28 },
      ],
    },
    {
      id: 'asian-handicap',
      name: 'Азиатская фора',
      category: 'main',
      layout: 'table',
      outcomes: [
        { label: 'Ф1 -0.75', odds: 2.10 },
        { label: 'Ф2 +0.75', odds: 1.70 },
        { label: 'Ф1 -1.25', odds: 2.55 },
        { label: 'Ф2 +1.25', odds: 1.48 },
        { label: 'Ф1 -0.25', odds: 1.88 },
        { label: 'Ф2 +0.25', odds: 1.92 },
        { label: 'Ф1 +0.25', odds: 1.45 },
        { label: 'Ф2 -0.25', odds: 2.65 },
      ],
    },
    // === 1ST HALF ===
    {
      id: '1st-half-1x2',
      name: '1-й тайм. Основные исходы',
      category: '1st-half',
      layout: 'grid',
      outcomes: [
        { label: 'П1 (1-й тайм)', odds: +(m['1'] * 1.15).toFixed(2) },
        { label: 'X (1-й тайм)', odds: +(m.x * 0.85).toFixed(2) },
        { label: 'П2 (1-й тайм)', odds: +(m['2'] * 1.15).toFixed(2) },
      ],
    },
    {
      id: '1st-half-total',
      name: '1-й тайм. Тотал',
      category: '1st-half',
      layout: 'table',
      outcomes: [
        { label: 'ТБ 0.5 (1Т)', odds: 1.35 },
        { label: 'ТМ 0.5 (1Т)', odds: 3.20 },
        { label: 'ТБ 1.5 (1Т)', odds: 2.45 },
        { label: 'ТМ 1.5 (1Т)', odds: 1.52 },
      ],
    },
    {
      id: '2nd-half-1x2',
      name: '2-й тайм. Основные исходы',
      category: '2nd-half',
      layout: 'grid',
      outcomes: [
        { label: 'П1 (2-й тайм)', odds: +(m['1'] * 1.1).toFixed(2) },
        { label: 'X (2-й тайм)', odds: +(m.x * 0.9).toFixed(2) },
        { label: 'П2 (2-й тайм)', odds: +(m['2'] * 1.1).toFixed(2) },
      ],
    },
    // === COMBO (under main) ===
    {
      id: '1x2-btts',
      name: '1X2 + обе забьют',
      category: 'main',
      layout: 'combo',
      outcomes: [
        { label: 'П1 и обе забьют - Да', odds: 5.78 },
        { label: 'П1 и обе забьют - Нет', odds: 1.82 },
        { label: 'X и обе забьют - Да', odds: 4.25 },
        { label: 'X и обе забьют - Нет', odds: 2.10 },
        { label: 'П2 и обе забьют - Да', odds: 3.40 },
        { label: 'П2 и обе забьют - Нет', odds: 1.55 },
      ],
    },
    {
      id: 'winner-total',
      name: 'Победа + Тотал (2.5)',
      category: 'main',
      layout: 'combo',
      outcomes: [
        { label: 'П1 + ТБ 2.5', odds: 3.80 },
        { label: 'П1 + ТМ 2.5', odds: 2.45 },
        { label: 'X + ТБ 2.5', odds: 5.50 },
        { label: 'X + ТМ 2.5', odds: 2.80 },
        { label: 'П2 + ТБ 2.5', odds: 4.20 },
        { label: 'П2 + ТМ 2.5', odds: 2.60 },
      ],
    },
    {
      id: 'winner-btts',
      name: 'Победа + Обе забьют',
      category: 'main',
      layout: 'combo',
      outcomes: [
        { label: 'П1 и Да', odds: 3.50 },
        { label: 'П1 и Нет', odds: 2.20 },
        { label: 'П2 и Да', odds: 4.10 },
        { label: 'П2 и Нет', odds: 1.90 },
      ],
    },
    // === INTERVALS (under main) ===
    {
      id: 'intervals-15',
      name: 'Интервалы. 1-15 мин',
      category: 'main',
      layout: 'grid',
      outcomes: [
        { label: 'Гол 1-15 Да', odds: 3.20 },
        { label: 'Гол 1-15 Нет', odds: 1.30 },
      ],
    },
    {
      id: 'intervals-16-30',
      name: 'Интервалы. 16-30 мин',
      category: 'main',
      layout: 'grid',
      outcomes: [
        { label: 'Гол 16-30 Да', odds: 2.80 },
        { label: 'Гол 16-30 Нет', odds: 1.40 },
      ],
    },
    {
      id: 'intervals-31-45',
      name: 'Интервалы. 31-45 мин',
      category: 'main',
      layout: 'grid',
      outcomes: [
        { label: 'Гол 31-45 Да', odds: 2.50 },
        { label: 'Гол 31-45 Нет', odds: 1.48 },
      ],
    },
    {
      id: 'intervals-46-60',
      name: 'Интервалы. 46-60 мин',
      category: 'main',
      layout: 'grid',
      outcomes: [
        { label: 'Гол 46-60 Да', odds: 2.40 },
        { label: 'Гол 46-60 Нет', odds: 1.52 },
      ],
    },
    {
      id: 'intervals-61-75',
      name: 'Интервалы. 61-75 мин',
      category: 'main',
      layout: 'grid',
      outcomes: [
        { label: 'Гол 61-75 Да', odds: 2.30 },
        { label: 'Гол 61-75 Нет', odds: 1.58 },
      ],
    },
    {
      id: 'intervals-76-90',
      name: 'Интервалы. 76-90 мин',
      category: 'main',
      layout: 'grid',
      outcomes: [
        { label: 'Гол 76-90 Да', odds: 2.20 },
        { label: 'Гол 76-90 Нет', odds: 1.62 },
      ],
    },
    // === CORNERS ===
    {
      id: 'corners-total',
      name: 'Угловые. Тотал',
      category: 'corners',
      layout: 'table',
      outcomes: [
        { label: 'ТБ 7.5 (уг)', odds: 1.75 },
        { label: 'ТМ 7.5 (уг)', odds: 2.05 },
        { label: 'ТБ 8.5 (уг)', odds: 2.10 },
        { label: 'ТМ 8.5 (уг)', odds: 1.72 },
        { label: 'ТБ 9.5 (уг)', odds: 2.45 },
        { label: 'ТМ 9.5 (уг)', odds: 1.55 },
        { label: 'ТБ 10.5 (уг)', odds: 2.80 },
        { label: 'ТМ 10.5 (уг)', odds: 1.42 },
      ],
    },
    {
      id: 'corners-1x2',
      name: 'Угловые. Победа по угловым',
      category: 'corners',
      layout: 'grid',
      outcomes: [
        { label: 'П1 (угловые)', odds: 1.90 },
        { label: 'X (угловые)', odds: 3.20 },
        { label: 'П2 (угловые)', odds: 2.05 },
      ],
    },
    {
      id: 'corners-handicap',
      name: 'Угловые. Фора',
      category: 'corners',
      layout: 'table',
      outcomes: [
        { label: 'Ф1 -1 (уг)', odds: 2.10 },
        { label: 'Ф2 +1 (уг)', odds: 1.75 },
        { label: 'Ф1 +1 (уг)', odds: 1.65 },
        { label: 'Ф2 -1 (уг)', odds: 2.25 },
      ],
    },
    // === CARDS ===
    {
      id: 'cards-total',
      name: 'Жёлтые карточки. Тотал',
      category: 'cards',
      layout: 'table',
      outcomes: [
        { label: 'ТБ 2.5 (жк)', odds: 1.80 },
        { label: 'ТМ 2.5 (жк)', odds: 2.00 },
        { label: 'ТБ 3.5 (жк)', odds: 2.30 },
        { label: 'ТМ 3.5 (жк)', odds: 1.60 },
        { label: 'ТБ 4.5 (жк)', odds: 3.10 },
        { label: 'ТМ 4.5 (жк)', odds: 1.35 },
        { label: 'ТБ 5.5 (жк)', odds: 4.20 },
        { label: 'ТМ 5.5 (жк)', odds: 1.22 },
      ],
    },
    {
      id: 'cards-1x2',
      name: 'Жёлтые карточки. Победа',
      category: 'cards',
      layout: 'grid',
      outcomes: [
        { label: 'П1 (жк)', odds: 2.20 },
        { label: 'X (жк)', odds: 3.50 },
        { label: 'П2 (жк)', odds: 1.85 },
      ],
    },
    {
      id: 'cards-team1',
      name: 'Жёлтые карточки. Команда 1',
      category: 'cards',
      layout: 'table',
      outcomes: [
        { label: 'ТБ1 0.5 (жк)', odds: 1.40 },
        { label: 'ТМ1 0.5 (жк)', odds: 2.80 },
        { label: 'ТБ1 1.5 (жк)', odds: 2.50 },
        { label: 'ТМ1 1.5 (жк)', odds: 1.50 },
      ],
    },
    // === PLAYERS ===
    {
      id: 'player-goal',
      name: 'Игроки. Забьёт гол',
      category: 'players',
      layout: 'combo',
      outcomes: [
        { label: 'Игрок 1 - Да', odds: 2.50 },
        { label: 'Игрок 1 - Нет', odds: 1.50 },
        { label: 'Игрок 2 - Да', odds: 3.20 },
        { label: 'Игрок 2 - Нет', odds: 1.32 },
        { label: 'Игрок 3 - Да', odds: 2.80 },
        { label: 'Игрок 3 - Нет', odds: 1.42 },
      ],
    },
    {
      id: 'player-yellow',
      name: 'Игроки. Получит жёлтую',
      category: 'players',
      layout: 'combo',
      outcomes: [
        { label: 'Игрок 1 - Да', odds: 3.50 },
        { label: 'Игрок 1 - Нет', odds: 1.28 },
        { label: 'Игрок 2 - Да', odds: 4.20 },
        { label: 'Игрок 2 - Нет', odds: 1.22 },
      ],
    },
    // === 2nd HALF extra ===
    {
      id: '2nd-half-total',
      name: '2-й тайм. Тотал',
      category: '2nd-half',
      layout: 'table',
      outcomes: [
        { label: 'ТБ 0.5 (2Т)', odds: 1.40 },
        { label: 'ТМ 0.5 (2Т)', odds: 2.80 },
        { label: 'ТБ 1.5 (2Т)', odds: 2.60 },
        { label: 'ТМ 1.5 (2Т)', odds: 1.48 },
      ],
    },
    // === FOULS ===
    {
      id: 'fouls-total',
      name: 'Фолы. Тотал',
      category: 'fouls',
      layout: 'table',
      outcomes: [
        { label: 'ТБ 16.5 (фол)', odds: 1.85 },
        { label: 'ТМ 16.5 (фол)', odds: 1.95 },
        { label: 'ТБ 18.5 (фол)', odds: 2.20 },
        { label: 'ТМ 18.5 (фол)', odds: 1.65 },
        { label: 'ТБ 20.5 (фол)', odds: 2.60 },
        { label: 'ТМ 20.5 (фол)', odds: 1.45 },
        { label: 'ТБ 22.5 (фол)', odds: 3.10 },
        { label: 'ТМ 22.5 (фол)', odds: 1.35 },
      ],
    },
    {
      id: 'fouls-1x2',
      name: 'Фолы. Победа по фолам',
      category: 'fouls',
      layout: 'grid',
      outcomes: [
        { label: 'П1 (фолы)', odds: 1.95 },
        { label: 'X (фолы)', odds: 3.10 },
        { label: 'П2 (фолы)', odds: 2.00 },
      ],
    },
    {
      id: 'fouls-handicap',
      name: 'Фолы. Фора',
      category: 'fouls',
      layout: 'table',
      outcomes: [
        { label: 'Ф1 -1.5 (фол)', odds: 2.10 },
        { label: 'Ф2 +1.5 (фол)', odds: 1.72 },
        { label: 'Ф1 +1.5 (фол)', odds: 1.68 },
        { label: 'Ф2 -1.5 (фол)', odds: 2.15 },
      ],
    },
    // === SHOTS ON TARGET ===
    {
      id: 'shots-total',
      name: 'Удары в створ. Тотал',
      category: 'shots',
      layout: 'table',
      outcomes: [
        { label: 'ТБ 4.5 (уд)', odds: 1.75 },
        { label: 'ТМ 4.5 (уд)', odds: 2.05 },
        { label: 'ТБ 5.5 (уд)', odds: 2.15 },
        { label: 'ТМ 5.5 (уд)', odds: 1.70 },
        { label: 'ТБ 6.5 (уд)', odds: 2.55 },
        { label: 'ТМ 6.5 (уд)', odds: 1.50 },
        { label: 'ТБ 7.5 (уд)', odds: 3.00 },
        { label: 'ТМ 7.5 (уд)', odds: 1.38 },
      ],
    },
    {
      id: 'shots-1x2',
      name: 'Удары в створ. Победа',
      category: 'shots',
      layout: 'grid',
      outcomes: [
        { label: 'П1 (удары)', odds: 1.80 },
        { label: 'X (удары)', odds: 3.40 },
        { label: 'П2 (удары)', odds: 2.15 },
      ],
    },
    {
      id: 'shots-team1',
      name: 'Удары в створ. Команда 1',
      category: 'shots',
      layout: 'table',
      outcomes: [
        { label: 'ТБ1 2.5 (уд)', odds: 1.90 },
        { label: 'ТМ1 2.5 (уд)', odds: 1.85 },
        { label: 'ТБ1 3.5 (уд)', odds: 2.40 },
        { label: 'ТМ1 3.5 (уд)', odds: 1.55 },
      ],
    },
    // === OFFSIDES ===
    {
      id: 'offsides-total',
      name: 'Офсайды. Тотал',
      category: 'offsides',
      layout: 'table',
      outcomes: [
        { label: 'ТБ 1.5 (оф)', odds: 1.70 },
        { label: 'ТМ 1.5 (оф)', odds: 2.10 },
        { label: 'ТБ 2.5 (оф)', odds: 2.25 },
        { label: 'ТМ 2.5 (оф)', odds: 1.62 },
        { label: 'ТБ 3.5 (оф)', odds: 2.90 },
        { label: 'ТМ 3.5 (оф)', odds: 1.40 },
      ],
    },
    {
      id: 'offsides-1x2',
      name: 'Офсайды. Победа',
      category: 'offsides',
      layout: 'grid',
      outcomes: [
        { label: 'П1 (офсайды)', odds: 1.85 },
        { label: 'X (офсайды)', odds: 3.20 },
        { label: 'П2 (офсайды)', odds: 2.05 },
      ],
    },
    // === THROW-INS ===
    {
      id: 'throw-ins-total',
      name: 'Ауты. Тотал',
      category: 'throw-ins',
      layout: 'table',
      outcomes: [
        { label: 'ТБ 18.5 (аут)', odds: 1.80 },
        { label: 'ТМ 18.5 (аут)', odds: 2.00 },
        { label: 'ТБ 22.5 (аут)', odds: 2.20 },
        { label: 'ТМ 22.5 (аут)', odds: 1.65 },
        { label: 'ТБ 26.5 (аут)', odds: 2.70 },
        { label: 'ТМ 26.5 (аут)', odds: 1.45 },
      ],
    },
    {
      id: 'throw-ins-1x2',
      name: 'Ауты. Победа',
      category: 'throw-ins',
      layout: 'grid',
      outcomes: [
        { label: 'П1 (ауты)', odds: 1.90 },
        { label: 'X (ауты)', odds: 3.00 },
        { label: 'П2 (ауты)', odds: 2.00 },
      ],
    },
    // === STATISTICS ===
    {
      id: 'stats-possession',
      name: 'Статистика. Владение мячом',
      category: 'statistics',
      layout: 'grid',
      outcomes: [
        { label: 'П1 (владение)', odds: 1.75 },
        { label: 'X (владение)', odds: 3.50 },
        { label: 'П2 (владение)', odds: 2.25 },
      ],
    },
    {
      id: 'stats-attacks',
      name: 'Статистика. Опасные атаки',
      category: 'statistics',
      layout: 'table',
      outcomes: [
        { label: 'ТБ 55.5 (ат)', odds: 1.85 },
        { label: 'ТМ 55.5 (ат)', odds: 1.95 },
        { label: 'ТБ 65.5 (ат)', odds: 2.30 },
        { label: 'ТМ 65.5 (ат)', odds: 1.60 },
      ],
    },
    {
      id: 'stats-xg',
      name: 'Статистика. Ожидаемые голы (xG)',
      category: 'statistics',
      layout: 'table',
      outcomes: [
        { label: 'ТБ 1.5 (xG)', odds: 1.70 },
        { label: 'ТМ 1.5 (xG)', odds: 2.10 },
        { label: 'ТБ 2.5 (xG)', odds: 2.40 },
        { label: 'ТМ 2.5 (xG)', odds: 1.55 },
      ],
    },
  ];
}

export const liveMatches: MatchEvent[] = [
  {
    id: 'l1',
    sport: 'football',
    league: 'АПЛ',
    country: 'Англия',
    team1: 'Манчестер Сити',
    team2: 'Арсенал',
    team1Color: '#6CABDD',
    team2Color: '#EF0107',
    startTime: now - 2700000,
    isLive: true,
    liveStatus: '1-й тайм, прошло 24:01',
    liveScore: { team1: 2, team2: 1 },
    markets: { '1': 1.45, x: 4.2, '2': 5.5 },
    extraMarkets: 184,
    featured: true,
    marketGroups: buildMarketGroups({ '1': 1.45, x: 4.2, '2': 5.5 }),
    stats: commonStats,
    h2h: commonH2H,
    stadium: { name: 'Etihad Stadium', city: 'Манчестер', capacity: '53 400' },
  },
  {
    id: 'l2',
    sport: 'basketball',
    league: 'NBA',
    country: 'США',
    team1: 'Лейкерс',
    team2: 'Бостон',
    team1Color: '#552583',
    team2Color: '#007A33',
    startTime: now - 3600000,
    isLive: true,
    liveStatus: '3-я четверть, 04:32',
    liveScore: { team1: 78, team2: 82 },
    markets: { '1': 2.1, x: 0, '2': 1.75 },
    extraMarkets: 142,
    marketGroups: buildMarketGroups({ '1': 2.1, x: 3.0, '2': 1.75 }),
    stats: [
      { label: 'Броски с игры', team1: '47%', team2: '52%' },
      { label: '3-очковые', team1: '38%', team2: '41%' },
      { label: 'Подборы', team1: 34, team2: 29 },
      { label: 'Передачи', team1: 22, team2: 25 },
    ],
    h2h: [
      { date: '20.03.25', result: 'Победа Бостон', score: '108:112' },
      { date: '15.12.24', result: 'Победа Лейкерс', score: '114:105' },
    ],
    stadium: { name: 'Crypto.com Arena', city: 'Лос-Анджелес', capacity: '20 000' },
  },
  {
    id: 'l3',
    sport: 'tennis',
    league: 'ATP 1000',
    country: 'Мадрид',
    team1: 'Алькарас',
    team2: 'Синнер',
    team1Color: '#E5A00D',
    team2Color: '#EF4444',
    startTime: now - 1800000,
    isLive: true,
    liveStatus: '2-й сет, 4:3',
    liveScore: { team1: 1, team2: 1 },
    markets: { '1': 1.85, x: 0, '2': 1.95 },
    extraMarkets: 56,
    marketGroups: buildMarketGroups({ '1': 1.85, x: 2.5, '2': 1.95 }),
    stats: [
      { label: 'Эйсы', team1: 8, team2: 5 },
      { label: 'Точность 1-й подачи', team1: '72%', team2: '68%' },
      { label: 'Брейк-пойнты', team1: '3/5', team2: '1/4' },
    ],
    h2h: [
      { date: '10.06.25', result: 'Победа Алькарас', score: '2:1' },
      { date: '22.03.25', result: 'Победа Синнер', score: '0:2' },
    ],
    stadium: { name: 'Caja Magica', city: 'Мадрид', capacity: '12 500' },
  },
  {
    id: 'l4',
    sport: 'football',
    league: 'Ла Лига',
    country: 'Испания',
    team1: 'Реал Мадрид',
    team2: 'Барселона',
    team1Color: '#FEBE10',
    team2Color: '#A50044',
    startTime: now - 1800000,
    isLive: true,
    liveStatus: '1-й тайм, прошло 12:15',
    liveScore: { team1: 0, team2: 0 },
    markets: { '1': 2.4, x: 3.3, '2': 2.9 },
    extraMarkets: 201,
    featured: true,
    marketGroups: buildMarketGroups({ '1': 2.4, x: 3.3, '2': 2.9 }),
    stats: commonStats,
    h2h: [
      { date: '27.04.25', result: 'Победа Реал', score: '3:2' },
      { date: '29.10.24', result: 'Победа Барселона', score: '0:4' },
      { date: '22.04.24', result: 'Ничья', score: '1:1' },
    ],
    stadium: { name: 'Santiago Bernabéu', city: 'Мадрид', capacity: '78 297' },
  },
  {
    id: 'l5',
    sport: 'hockey',
    league: 'НХЛ',
    country: 'США',
    team1: 'Рейнджерс',
    team2: 'Питтсбург',
    team1Color: '#0038A8',
    team2Color: '#FCB514',
    startTime: now - 2400000,
    isLive: true,
    liveStatus: '2-й период, 08:21',
    liveScore: { team1: 3, team2: 2 },
    markets: { '1': 2.25, x: 3.8, '2': 2.55 },
    extraMarkets: 98,
    marketGroups: buildMarketGroups({ '1': 2.25, x: 3.8, '2': 2.55 }),
    stats: [
      { label: 'Броски в створ', team1: 18, team2: 14 },
      { label: 'Штрафное время', team1: '6 мин', team2: '12 мин' },
      { label: 'Силовые приёмы', team1: 15, team2: 12 },
    ],
    h2h: [
      { date: '14.02.25', result: 'Победа Рейнджерс', score: '4:1' },
      { date: '08.11.24', result: 'Победа Питтсбург', score: '2:3' },
    ],
    stadium: { name: 'Madison Square Garden', city: 'Нью-Йорк', capacity: '18 006' },
  },
  {
    id: 'l6',
    sport: 'esports',
    league: 'CS2 Major',
    country: 'Международный',
    team1: 'NaVi',
    team2: 'Vitality',
    team1Color: '#FFE600',
    team2Color: '#FFD700',
    startTime: now - 1200000,
    isLive: true,
    liveStatus: 'Карта 2, Mirage',
    liveScore: { team1: 1, team2: 0 },
    markets: { '1': 1.65, x: 0, '2': 2.2 },
    extraMarkets: 73,
    marketGroups: buildMarketGroups({ '1': 1.65, x: 2.5, '2': 2.2 }),
    stats: [
      { label: 'Раунды выиграно', team1: 13, team2: 9 },
      { label: 'K/D', team1: '1.15', team2: '0.92' },
      { label: 'Первые убийства', team1: 5, team2: 3 },
    ],
    h2h: [
      { date: '01.07.25', result: 'Победа NaVi', score: '2:0' },
      { date: '15.05.25', result: 'Победа Vitality', score: '1:2' },
    ],
    stadium: { name: 'Online', city: 'Counter-Strike 2', capacity: '—' },
    hasStream: true,
  },
];

export const upcomingMatches: MatchEvent[] = [
  {
    id: 'u1',
    sport: 'football',
    league: 'Лига Чемпионов',
    country: 'Европа',
    team1: 'ПСЖ',
    team2: 'Бавария',
    team1Color: '#004170',
    team2Color: '#DC052D',
    startTime: now + 7200000,
    isLive: false,
    markets: { '1': 2.5, x: 3.4, '2': 2.7 },
    extraMarkets: 256,
    featured: true,
    marketGroups: buildMarketGroups({ '1': 2.5, x: 3.4, '2': 2.7 }),
    stats: commonStats,
    h2h: [
      { date: '05.04.25', result: 'Победа ПСЖ', score: '2:0' },
      { date: '12.11.24', result: 'Победа Бавария', score: '1:3' },
    ],
    stadium: { name: 'Parc des Princes', city: 'Париж', capacity: '47 929' },
  },
  {
    id: 'u2',
    sport: 'football',
    league: 'Серия А',
    country: 'Италия',
    team1: 'Интер',
    team2: 'Милан',
    team1Color: '#0068A8',
    team2Color: '#FB090B',
    startTime: now + 10800000,
    isLive: false,
    markets: { '1': 1.9, x: 3.5, '2': 3.8 },
    extraMarkets: 198,
    marketGroups: buildMarketGroups({ '1': 1.9, x: 3.5, '2': 3.8 }),
    stats: commonStats,
    h2h: [
      { date: '03.02.25', result: 'Ничья', score: '1:1' },
      { date: '20.09.24', result: 'Победа Интер', score: '2:0' },
    ],
    stadium: { name: 'San Siro', city: 'Милан', capacity: '75 923' },
  },
  {
    id: 'u3',
    sport: 'football',
    league: 'Бундеслига',
    country: 'Германия',
    team1: 'Боруссия Д',
    team2: 'Лейпциг',
    team1Color: '#FDE100',
    team2Color: '#DD0741',
    startTime: now + 14400000,
    isLive: false,
    markets: { '1': 1.7, x: 4.0, '2': 4.5 },
    extraMarkets: 167,
    marketGroups: buildMarketGroups({ '1': 1.7, x: 4.0, '2': 4.5 }),
    stats: commonStats,
    h2h: [
      { date: '18.01.25', result: 'Победа Боруссия Д', score: '3:1' },
      { date: '06.10.24', result: 'Победа Лейпциг', score: '0:2' },
    ],
    stadium: { name: 'Signal Iduna Park', city: 'Дортмунд', capacity: '81 365' },
  },
  {
    id: 'u4',
    sport: 'basketball',
    league: 'Евролига',
    country: 'Европа',
    team1: 'ЦСКА',
    team2: 'Реал',
    team1Color: '#1A4DA1',
    team2Color: '#FEBE10',
    startTime: now + 9000000,
    isLive: false,
    markets: { '1': 2.05, x: 0, '2': 1.8 },
    extraMarkets: 112,
    marketGroups: buildMarketGroups({ '1': 2.05, x: 3.0, '2': 1.8 }),
    stats: [],
    h2h: [],
    stadium: { name: 'CSKA Arena', city: 'Москва', capacity: '12 000' },
  },
  {
    id: 'u5',
    sport: 'tennis',
    league: 'WTA 500',
    country: 'Сан-Диего',
    team1: 'Швёнтек',
    team2: 'Сабаленка',
    team1Color: '#E5A00D',
    team2Color: '#EF4444',
    startTime: now + 5400000,
    isLive: false,
    markets: { '1': 1.55, x: 0, '2': 2.45 },
    extraMarkets: 64,
    marketGroups: buildMarketGroups({ '1': 1.55, x: 2.5, '2': 2.45 }),
    stats: [],
    h2h: [],
    stadium: { name: 'Barnsdall Court', city: 'Сан-Диего', capacity: '5 000' },
  },
  {
    id: 'u6',
    sport: 'mma',
    league: 'UFC 312',
    country: 'Лас-Вегас',
    team1: 'Махачев',
    team2: 'Топурия',
    team1Color: '#D49000',
    team2Color: '#EF4444',
    startTime: now + 86400000,
    isLive: false,
    markets: { '1': 1.72, x: 0, '2': 2.1 },
    extraMarkets: 38,
    featured: true,
    marketGroups: buildMarketGroups({ '1': 1.72, x: 2.5, '2': 2.1 }),
    stats: [],
    h2h: [],
    stadium: { name: 'T-Mobile Arena', city: 'Лас-Вегас', capacity: '20 000' },
  },
  {
    id: 'u7',
    sport: 'hockey',
    league: 'КХЛ',
    country: 'Россия',
    team1: 'СКА',
    team2: 'Динамо М',
    team1Color: '#E5A00D',
    team2Color: '#005BAA',
    startTime: now + 12600000,
    isLive: false,
    markets: { '1': 1.95, x: 3.9, '2': 3.2 },
    extraMarkets: 87,
    marketGroups: buildMarketGroups({ '1': 1.95, x: 3.9, '2': 3.2 }),
    stats: [],
    h2h: [],
    stadium: { name: 'Ледовый дворец', city: 'Санкт-Петербург', capacity: '12 300' },
  },
  {
    id: 'u8',
    sport: 'esports',
    league: 'Dota 2 ESL',
    country: 'Международный',
    team1: 'Team Spirit',
    team2: 'Gaimin Gladiators',
    team1Color: '#FFD700',
    team2Color: '#3B82F6',
    startTime: now + 7200000,
    isLive: false,
    markets: { '1': 1.8, x: 0, '2': 2.0 },
    extraMarkets: 52,
    marketGroups: buildMarketGroups({ '1': 1.8, x: 2.5, '2': 2.0 }),
    stats: [],
    h2h: [],
    stadium: { name: 'Online', city: 'Dota 2', capacity: '—' },
  },
];

export const allMatches = [...liveMatches, ...upcomingMatches];

export function getMatchById(id: string): MatchEvent | undefined {
  return allMatches.find((m) => m.id === id);
}

export const casinoGames: CasinoGame[] = [
  { id: 'c1', name: 'Sweet Bonanza', provider: 'Pragmatic Play', category: 'Слоты', rtp: '96.5%', hot: true, color: '#EC4899' },
  { id: 'c2', name: 'Gates of Olympus', provider: 'Pragmatic Play', category: 'Слоты', rtp: '96.5%', hot: true, color: '#8B5CF6' },
  { id: 'c3', name: 'Crazy Time', provider: 'Evolution', category: 'Live', rtp: '95.4%', hot: true, color: '#EF4444' },
  { id: 'c4', name: 'Aviator', provider: 'Nextpari Originals', category: 'Crash', rtp: '97.0%', hot: true, color: '#A855F7', cover: '/images/games/aviator.png' },
  { id: 'apples', name: 'Apple of Fortune', provider: 'Nextpari Originals', category: 'Originals', rtp: '96.0%', hot: true, color: '#22C55E', cover: '/images/games/apple_banner.png' },
  { id: 'crystal', name: 'Crystal', provider: 'Nextpari Originals', category: 'Originals', rtp: '96.0%', hot: true, color: '#22D3EE', cover: '/images/games/crystal_banner.png' },
  { id: 'c5', name: 'Big Bass Bonanza', provider: 'Pragmatic Play', category: 'Слоты', rtp: '96.7%', color: '#0EA5E9' },
  { id: 'c6', name: 'Mega Moolah', provider: 'Microgaming', category: 'Jackpot', rtp: '88.1%', color: '#EAB308' },
  { id: 'c7', name: 'Lightning Roulette', provider: 'Evolution', category: 'Live', rtp: '97.3%', color: '#F97316' },
  { id: 'c8', name: 'JetX', provider: 'SmartSoft', category: 'Crash', rtp: '97.0%', new: true, color: '#3B82F6' },
  { id: 'c9', name: 'Wolf Gold', provider: 'Pragmatic Play', category: 'Слоты', rtp: '96.0%', color: '#D97706' },
  { id: 'c10', name: 'Book of Dead', provider: "Play'n GO", category: 'Слоты', rtp: '96.2%', color: '#7C3AED' },
  { id: 'c11', name: 'Plinko', provider: 'Spribe', category: 'Mini', rtp: '97.0%', new: true, color: '#14B8A6' },
  { id: 'c12', name: 'Monopoly Live', provider: 'Evolution', category: 'Live', rtp: '96.2%', color: '#0891B2' },
];

export const transactions: Transaction[] = [
  { id: 't1', type: 'deposit', title: 'Пополнение счёта', date: '10 авг, 14:32', amount: 5000, status: 'completed' },
  { id: 't2', type: 'bet', title: 'Ставка: Манчестер Сити — Арсенал', date: '10 авг, 14:15', amount: -1000, status: 'completed' },
  { id: 't3', type: 'win', title: 'Выигрыш: Реал — Барселона', date: '09 авг, 22:40', amount: 2450, status: 'completed' },
  { id: 't4', type: 'bet', title: 'Ставка: Лейкерс — Бостон', date: '09 авг, 20:00', amount: -500, status: 'completed' },
  { id: 't5', type: 'withdraw', title: 'Вывод средств', date: '08 авг, 16:20', amount: -3000, status: 'processing' },
  { id: 't6', type: 'deposit', title: 'Пополнение по карте', date: '07 авг, 10:05', amount: 2000, status: 'completed' },
  { id: 't7', type: 'bet', title: 'Ставка: Алькарас — Синнер', date: '06 авг, 19:30', amount: -800, status: 'failed' },
  { id: 't8', type: 'win', title: 'Выигрыш: ПСЖ — Бавария', date: '05 авг, 23:15', amount: 1750, status: 'completed' },
  { id: 't9', type: 'deposit', title: 'Пополнение: Apple Pay', date: '04 авг, 09:45', amount: 10000, status: 'completed' },
  { id: 't10', type: 'withdraw', title: 'Вывод на карту', date: '03 авг, 15:10', amount: -5000, status: 'completed' },
];

export const championships: Championship[] = [
  { id: 'ch1', name: 'Лига Конференций УЕФА', country: 'Европа', flagColor: '#1A4DA1', matchCount: 8 },
  { id: 'ch2', name: 'Суперкубок Греции', country: 'Греция', flagColor: '#0D5EAF', matchCount: 2 },
  { id: 'ch3', name: 'Кубок Либертадорес', country: 'Южная Америка', flagColor: '#EAB308', matchCount: 6 },
  { id: 'ch4', name: 'Про Лига Саудовской Аравии', country: 'Саудовская Аравия', flagColor: '#16A34A', matchCount: 5 },
  { id: 'ch5', name: 'Бундеслига 2', country: 'Германия', flagColor: '#DC052D', matchCount: 9 },
  { id: 'ch6', name: 'Сегунда', country: 'Испания', flagColor: '#AA151B', matchCount: 11 },
];

export const casinoCategories: CasinoCategory[] = [
  { id: 'cat1', name: 'Слоты', gradient: 'from-violet-500 to-purple-700' },
  { id: 'cat2', name: 'Лайв казино', gradient: 'from-red-500 to-rose-700' },
  { id: 'cat3', name: 'TV игры', gradient: 'from-blue-500 to-indigo-700' },
  { id: 'cat4', name: 'Бинго', gradient: 'from-brand-500 to-accent-700' },
];

export const esportsDisciplines: EsportsDiscipline[] = [
  { id: 'd1', name: 'CS 2', gradient: 'from-slate-600 to-slate-900' },
  { id: 'd2', name: 'Dota 2', gradient: 'from-red-600 to-red-900' },
  { id: 'd3', name: 'League of Legends', gradient: 'from-cyan-500 to-blue-800' },
  { id: 'd4', name: 'Valorant', gradient: 'from-pink-500 to-rose-800' },
];

export const esportsLiveMatches: MatchEvent[] = [
  {
    id: 'el1',
    sport: 'esports',
    league: 'CS2 ESL Pro',
    country: 'Международный',
    team1: 'Natus Vincere',
    team2: '3DMAX',
    team1Color: '#FFE600',
    team2Color: '#FF6B35',
    startTime: now - 1800000,
    isLive: true,
    liveStatus: 'Карта 1, Nuke',
    liveScore: { team1: 1, team2: 0 },
    markets: { '1': 1.55, x: 0, '2': 2.4 },
    extraMarkets: 64,
    marketGroups: buildMarketGroups({ '1': 1.55, x: 2.5, '2': 2.4 }),
    stats: [
      { label: 'Раунды выиграно', team1: 11, team2: 7 },
      { label: 'K/D', team1: '1.22', team2: '0.85' },
    ],
    h2h: [],
    stadium: { name: 'Online', city: 'CS2', capacity: '—' },
    hasStream: true,
  },
  {
    id: 'el2',
    sport: 'esports',
    league: 'Dota 2 DreamLeague',
    country: 'Международный',
    team1: 'Tundra',
    team2: 'BetBoom',
    team1Color: '#3B82F6',
    team2Color: '#EF4444',
    startTime: now - 2400000,
    isLive: true,
    liveStatus: 'Игра 2, 28 мин',
    liveScore: { team1: 1, team2: 0 },
    markets: { '1': 1.7, x: 0, '2': 2.1 },
    extraMarkets: 48,
    marketGroups: buildMarketGroups({ '1': 1.7, x: 2.5, '2': 2.1 }),
    stats: [
      { label: 'Kills', team1: 24, team2: 18 },
      { label: 'Net worth', team1: '8.2k', team2: '5.1k' },
    ],
    h2h: [],
    stadium: { name: 'Online', city: 'Dota 2', capacity: '—' },
    hasStream: true,
  },
  {
    id: 'el3',
    sport: 'esports',
    league: 'LoL LCK',
    country: 'Корея',
    team1: 'T1',
    team2: 'Gen.G',
    team1Color: '#E4071E',
    team2Color: '#AA8300',
    startTime: now - 3000000,
    isLive: true,
    liveStatus: 'Игра 1, 22 мин',
    liveScore: { team1: 0, team2: 1 },
    markets: { '1': 2.0, x: 0, '2': 1.8 },
    extraMarkets: 36,
    marketGroups: buildMarketGroups({ '1': 2.0, x: 2.5, '2': 1.8 }),
    stats: [],
    h2h: [],
    stadium: { name: 'Online', city: 'LoL', capacity: '—' },
    hasStream: true,
  },
];

export const esportsUpcomingMatches: MatchEvent[] = [
  {
    id: 'eu1',
    sport: 'esports',
    league: 'CS2 BLAST Premier',
    country: 'Международный',
    team1: 'FaZe',
    team2: 'G2',
    team1Color: '#E41B1B',
    team2Color: '#0A0A0A',
    startTime: now + 10800000,
    isLive: false,
    markets: { '1': 1.9, x: 0, '2': 1.9 },
    extraMarkets: 72,
    marketGroups: buildMarketGroups({ '1': 1.9, x: 2.5, '2': 1.9 }),
    stats: [],
    h2h: [],
    stadium: { name: 'Online', city: 'CS2', capacity: '—' },
    hasStream: true,
  },
  {
    id: 'eu2',
    sport: 'esports',
    league: 'Dota 2 Riyadh Masters',
    country: 'Саудовская Аравия',
    team1: 'Team Spirit',
    team2: 'LGD',
    team1Color: '#FFD700',
    team2Color: '#8B5CF6',
    startTime: now + 14400000,
    isLive: false,
    markets: { '1': 1.65, x: 0, '2': 2.2 },
    extraMarkets: 58,
    marketGroups: buildMarketGroups({ '1': 1.65, x: 2.5, '2': 2.2 }),
    stats: [],
    h2h: [],
    stadium: { name: 'Online', city: 'Dota 2', capacity: '—' },
    hasStream: true,
  },
  {
    id: 'eu3',
    sport: 'esports',
    league: 'Valorant Champions',
    country: 'Международный',
    team1: 'Sentinels',
    team2: 'LOUD',
    team1Color: '#EC4899',
    team2Color: '#10B981',
    startTime: now + 18000000,
    isLive: false,
    markets: { '1': 2.1, x: 0, '2': 1.75 },
    extraMarkets: 44,
    marketGroups: buildMarketGroups({ '1': 2.1, x: 2.5, '2': 1.75 }),
    stats: [],
    h2h: [],
    stadium: { name: 'Online', city: 'Valorant', capacity: '—' },
    hasStream: true,
  },
];

export const allEsportsMatches = [...esportsLiveMatches, ...esportsUpcomingMatches];

export const betHistory: BetHistoryEntry[] = [
  {
    id: 'bh1',
    type: 'express',
    events: [
      { matchLabel: 'Манчестер Сити — Арсенал', market: '1X2', outcome: 'П1', odds: 1.85, finalScore: '2:1' },
      { matchLabel: 'Реал — Барселона', market: '1X2', outcome: 'П2', odds: 2.10, finalScore: '1:3' },
      { matchLabel: 'ПСЖ — Бавария', market: 'Тотал', outcome: 'ТБ 2.5', odds: 1.72, finalScore: '3:1' },
    ],
    totalOdds: 6.68,
    amount: 500,
    payout: 3340,
    status: 'won',
    date: '12 авг, 18:30',
    ticketCode: '4829173',
  },
  {
    id: 'bh2',
    type: 'single',
    events: [
      { matchLabel: 'Лейкерс — Бостон', market: 'Победа матча', outcome: 'П1', odds: 1.90, finalScore: '102:108' },
    ],
    totalOdds: 1.90,
    amount: 1000,
    payout: 0,
    status: 'lost',
    date: '11 авг, 22:15',
  },
  {
    id: 'bh3',
    type: 'express',
    events: [
      { matchLabel: 'Ювентус — Милан', market: '1X2', outcome: '1X', odds: 1.55 },
      { matchLabel: 'Атлетико — Севилья', market: '1X2', outcome: 'П1', odds: 2.05 },
    ],
    totalOdds: 3.18,
    amount: 800,
    payout: 0,
    cashout: 580,
    status: 'in_progress',
    date: '12 авг, 20:00',
    ticketCode: '7193048',
  },
  {
    id: 'bh4',
    type: 'single',
    events: [
      { matchLabel: 'Алькарас — Синнер', market: 'Победа матча', outcome: 'П2', odds: 2.40, finalScore: '3:1' },
    ],
    totalOdds: 2.40,
    amount: 600,
    payout: 1440,
    status: 'won',
    date: '10 авг, 19:30',
  },
  {
    id: 'bh5',
    type: 'single',
    events: [
      { matchLabel: 'Челси — Ливерпуль', market: 'Тотал', outcome: 'ТМ 2.5', odds: 1.88, finalScore: '3:2' },
    ],
    totalOdds: 1.88,
    amount: 750,
    payout: 0,
    status: 'lost',
    date: '09 авг, 17:45',
  },
  {
    id: 'bh6',
    type: 'express',
    events: [
      { matchLabel: 'Барселона — Сельта', market: '1X2', outcome: 'П1', odds: 1.65 },
      { matchLabel: 'Интер — Рома', market: '1X2', outcome: 'П1', odds: 1.78 },
    ],
    totalOdds: 2.94,
    amount: 400,
    payout: 0,
    cashout: 340,
    status: 'in_progress',
    date: '12 авг, 21:30',
    ticketCode: '3051842',
  },
];
